name: trusted-social

services:
  api:
    container_name: trusted-social-api
    build:
      context: ./
      dockerfile: dockerFiles/app_docker
    restart: always
    networks:
      - backend
      - shared_bridge
    env_file:
      - .env
    environment:
      LLM_URL: "http://host.docker.internal:11434/api/chat"
    extra_hosts:
      - "host.docker.internal:172.25.0.1"
    ports:
      - "8020:8020"
    volumes:
      - ./app/api:/app/api:cached
      - ./app/raw:/app/raw:cached
      - ./sessions:/app/sessions:cached
      - ./social-automation:/app/social-automation:cached
      - social_automation_node_modules:/app/social-automation/node_modules

    deploy:
      resources:
        limits:
          memory: 36G
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/8020' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  tor-extend-1:
    container_name: trusted-social_tor_instace_1
    image: barneybuffet/tor:latest
    env_file:
      - .env
    volumes:
      - ./config/tor/torrc_1.txt:/etc/tor/torrc:rw
    ports:
      - "0.0.0.0:9552:9552"
      - "0.0.0.0:9553:9553"
    environment:
      PUID: "20002"
      PGID: "20003"
      TOR_CONFIG_OVERWRITE: "true"
      TOR_LOG_CONFIG: "true"
      TOR_PROXYL: "true"
      TOR_PROXY_PORT: "0.0.0.0:9552"
      TOR_PROXY_SOCKET: "true"
      TOR_PROXY_ACCEPT: "accept 172.25.0.0/24,accept 127.0.0.1,accept 10.0.0.0/8,accept 172.16.0.0/12,accept 192.168.0.0/16"
      TOR_CONTROL: "true"
      TOR_CONTROL_PORT: "0.0.0.0:9553"
      TOR_CONTROL_SOCKET: "true"
      TOR_CONTROL_PASSWORD: ${TOR_PASSWORD}
      TOR_CONTROL_COOKIE: "true"
      TOR_RELAY: "false"
    networks:
      backend:
        ipv4_address: 172.25.0.10
    healthcheck:
      test: [ "CMD-SHELL", "curl --proxy socks5h://localhost:9552 http://example.com || exit 1" ]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  shared_bridge:
    external: true
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

volumes:
  social_automation_node_modules:
