import re

import api.social_manager.social_recon.custom_recon.core.registry as registry
from api.social_manager.social_recon.custom_recon.custom_recon import custom_recon
from app.probe.recon_probe.constant.recon_probe_constant import ReconProbeConstants

# one safe, well-known public url per ROUTES entry: (url, platform NAME, expected identity, expected entity type)
ROUTE_CASES = (
    ('https://bsky.app/profile/bsky.app/post/3kaaaaaaaaa2a', 'Bluesky', 'bsky.app', 'post'),
    ('https://bsky.app/profile/bsky.app', 'Bluesky', 'bsky.app', 'profile'),
    ('https://www.facebook.com/groups/facebook', 'Facebook', 'facebook', 'group'),
    ('https://www.facebook.com/facebook/posts/10150000000000000', 'Facebook', 'facebook', 'post'),
    ('https://www.facebook.com/profile.php?id=4', 'Facebook', '4', 'profile'),
    ('https://www.facebook.com/facebook', 'Facebook', 'facebook', 'profile'),
    ('https://www.instagram.com/p/CxYzAbC1234/', 'Instagram', 'CxYzAbC1234', 'post'),
    ('https://www.instagram.com/instagram/', 'Instagram', 'instagram', 'profile'),
    ('https://www.pinterest.com/pin/1/', 'Pinterest', '1', 'post'),
    ('https://www.pinterest.com/pinterest/', 'Pinterest', 'pinterest', 'profile'),
    ('https://www.quora.com/profile/Adam-DAngelo', 'Quora', 'Adam-DAngelo', 'profile'),
    ('https://www.quora.com/q/quora', 'Quora', 'quora', 'space'),
    ('https://www.quora.com/What-is-Quora', 'Quora', 'What-is-Quora', 'question'),
    ('https://www.reddit.com/user/spez', 'Reddit', 'spez', 'profile'),
    ('https://www.reddit.com/r/python/comments/abc123/title/', 'Reddit', 'abc123', 'post'),
    ('https://www.reddit.com/r/python', 'Reddit', 'python', 'subreddit'),
    ('https://www.threads.net/@zuck/post/CuZsgfWLyiI', 'Threads', 'zuck', 'post'),
    ('https://www.threads.net/@zuck', 'Threads', 'zuck', 'profile'),
    ('https://www.tiktok.com/@tiktok/video/1', 'TikTok', 'tiktok', 'post'),
    ('https://www.tiktok.com/@tiktok', 'TikTok', 'tiktok', 'profile'),
    ('https://www.twitch.tv/videos/1', 'Twitch', '1', 'video'),
    ('https://www.twitch.tv/twitch', 'Twitch', 'twitch', 'profile'),
    ('https://x.com/x/status/1', 'X', 'x', 'post'),
    ('https://twitter.com/x', 'X', 'x', 'profile'),
    ('https://www.youtube.com/@youtube', 'YouTube', 'youtube', 'profile'),
    ('https://www.youtube.com/channel/UCBR8-60-B28hp2BmDPdntcQ', 'YouTube', 'UCBR8-60-B28hp2BmDPdntcQ', 'channel'),
    ('https://www.youtube.com/shorts/dQw4w9WgXcQ', 'YouTube', 'dQw4w9WgXcQ', 'video'),
    ('https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'YouTube', 'dQw4w9WgXcQ', 'video'),
    ('https://ok.ru/profile/561551231571', 'OK.ru', '561551231571', 'profile'),
    ('https://ok.ru/group/53038939046008', 'OK.ru', '53038939046008', 'group'),
    ('https://ok.ru/video/1', 'OK.ru', '1', 'video'),
    ('https://ok.ru/ok', 'OK.ru', 'ok', 'profile'),
    ('https://www.bilibili.com/video/BV1GJ411x7h7', 'Bilibili', 'BV1GJ411x7h7', 'video'),
    ('https://space.bilibili.com/208259', 'Bilibili', '208259', 'profile'),
    ('https://tieba.baidu.com/home/main?un=baidu', 'Baidu Tieba', 'baidu', 'profile'),
    ('https://tieba.baidu.com/f?kw=python', 'Baidu Tieba', 'python', 'group'),
    ('https://tieba.baidu.com/p/1', 'Baidu Tieba', '1', 'post'),
    ('https://mastodon.social/@Mastodon/1', 'Mastodon', 'Mastodon', 'post'),
    ('https://mastodon.social/@Mastodon', 'Mastodon', 'Mastodon', 'profile'),
    ('https://mewe.com/i/mewe', 'MeWe', 'mewe', 'profile'),
    ('https://mewe.com/join/mewe', 'MeWe', 'mewe', 'group'),
    ('https://mewe.com/p/mewe', 'MeWe', 'mewe', 'page'),
    ('https://rumble.com/user/Rumble', 'Rumble', 'Rumble', 'profile'),
    ('https://rumble.com/c/Rumble', 'Rumble', 'Rumble', 'channel'),
    ('https://rumble.com/v1abc-hello.html', 'Rumble', 'v1abc', 'video'),
    ('https://kick.com/video/abc', 'Kick', 'abc', 'video'),
    ('https://kick.com/xqc/videos/abc', 'Kick', 'xqc', 'video'),
    ('https://kick.com/xqc', 'Kick', 'xqc', 'profile'),
    ('https://www.lemon8-app.com/@lemon8_us/1', 'Lemon8', 'lemon8_us', 'post'),
    ('https://www.lemon8-app.com/@lemon8_us', 'Lemon8', 'lemon8_us', 'profile'),
    ('https://vsco.co/vsco/media/1', 'VSCO', 'vsco', 'post'),
    ('https://vsco.co/vsco/gallery', 'VSCO', 'vsco', 'profile'),
    ('https://www.flickr.com/photos/flickr/1', 'Flickr', 'flickr', 'post'),
    ('https://www.flickr.com/groups/flickr', 'Flickr', 'flickr', 'group'),
    ('https://www.flickr.com/people/flickr', 'Flickr', 'flickr', 'profile'),
    ('https://www.behance.net/gallery/1/Project', 'Behance', '1', 'post'),
    ('https://www.behance.net/behance', 'Behance', 'behance', 'profile'),
    ('https://dribbble.com/shots/1-hello', 'Dribbble', '1-hello', 'post'),
    ('https://dribbble.com/dribbble', 'Dribbble', 'dribbble', 'profile'),
    ('https://imgur.com/gallery/abc123', 'Imgur', 'abc123', 'post'),
    ('https://imgur.com/user/imgur', 'Imgur', 'imgur', 'profile'),
    ('https://www.artstation.com/artwork/abc', 'ArtStation', 'abc', 'post'),
    ('https://www.artstation.com/artstation', 'ArtStation', 'artstation', 'profile'),
    ('https://bandcamp.com/album/hello', 'Bandcamp', 'hello', 'post'),
    ('https://bandcamp.com/bandcamp', 'Bandcamp', 'bandcamp', 'profile'),
    ('https://www.last.fm/user/rj', 'Last.fm', 'rj', 'profile'),
    ('https://www.last.fm/music/Radiohead', 'Last.fm', 'Radiohead', 'page'),
    ('https://www.goodreads.com/user/show/1-otis-chandler', 'Goodreads', '1-otis-chandler', 'profile'),
    ('https://www.goodreads.com/book/show/1', 'Goodreads', '1', 'post'),
    ('https://www.goodreads.com/group/show/1', 'Goodreads', '1', 'group'),
    ('https://www.goodreads.com/otis', 'Goodreads', 'otis', 'profile'),
    ('https://letterboxd.com/film/parasite-2019', 'Letterboxd', 'parasite-2019', 'post'),
    ('https://letterboxd.com/letterboxd', 'Letterboxd', 'letterboxd', 'profile'),
    ('https://independent.academia.edu/AlbertEinstein', 'Academia.edu', 'AlbertEinstein', 'profile'),
    ('https://stackoverflow.com/users/22656/jon-skeet', 'Stack Overflow', '22656', 'profile'),
    ('https://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster', 'Stack Overflow', '11227809', 'question'),
    ('https://stackexchange.com/users/1/jeff-atwood', 'Stack Exchange', '1', 'profile'),
    ('https://superuser.com/questions/1', 'Stack Exchange', '1', 'question'),
    ('https://github.com/orgs/github/repositories', 'GitHub', 'github', 'page'),
    ('https://github.com/torvalds/linux', 'GitHub', 'torvalds', 'repo'),
    ('https://github.com/torvalds', 'GitHub', 'torvalds', 'profile'),
    ('https://gitlab.com/groups/gitlab-org', 'GitLab', 'gitlab-org', 'group'),
    ('https://gitlab.com/gitlab-org/gitlab', 'GitLab', 'gitlab-org', 'repo'),
    ('https://gitlab.com/gitlab-bot', 'GitLab', 'gitlab-bot', 'profile'),
    ('https://news.ycombinator.com/user?id=pg', 'Hacker News', 'pg', 'profile'),
    ('https://news.ycombinator.com/item?id=1', 'Hacker News', '1', 'post'),
    ('https://www.producthunt.com/@rrhoover', 'Product Hunt', 'rrhoover', 'profile'),
    ('https://www.producthunt.com/posts/product-hunt', 'Product Hunt', 'product-hunt', 'post'),
    ('https://medium.com/@Medium/hello-1', 'Medium', 'Medium', 'post'),
    ('https://medium.com/@Medium', 'Medium', 'Medium', 'profile'),
    ('https://medium.com/the-story/hello-1', 'Medium', 'the-story', 'post'),
    ('https://medium.com/the-story', 'Medium', 'the-story', 'page'),
    ('https://substack.com/@substack', 'Substack', 'substack', 'profile'),
    ('https://substack.com/profile/1-substack', 'Substack', '1-substack', 'profile'),
    ('https://community.fandom.com/wiki/User:Fandom', 'Fandom', 'Fandom', 'profile'),
    ('https://community.fandom.com/wiki/Help:Contents', 'Fandom', 'Help:Contents', 'post'),
    ('https://steamcommunity.com/id/gabelogannewell', 'Steam Community', 'gabelogannewell', 'profile'),
    ('https://steamcommunity.com/groups/Valve', 'Steam Community', 'Valve', 'group'),
    ('https://steamcommunity.com/sharedfiles/filedetails?id=1', 'Steam Community', '1', 'post'),
    ('https://www.roblox.com/users/1/profile', 'Roblox', '1', 'profile'),
    ('https://www.roblox.com/users/profile?username=Roblox', 'Roblox', 'Roblox', 'profile'),
    ('https://www.roblox.com/groups/1200769/Roblox', 'Roblox', '1200769', 'group'),
    ('https://www.roblox.com/games/1818/Classic-Crossroads', 'Roblox', '1818', 'post'),
    ('https://gamejolt.com/@gamejolt', 'Game Jolt', 'gamejolt', 'profile'),
    ('https://gamejolt.com/games/hello/1', 'Game Jolt', 'hello', 'post'),
    ('https://gamejolt.com/c/gamedev', 'Game Jolt', 'gamedev', 'group'),
    ('https://myanimelist.net/profile/Xinil', 'MyAnimeList', 'Xinil', 'profile'),
    ('https://myanimelist.net/clubs.php?cid=1', 'MyAnimeList', '1', 'group'),
    ('https://myanimelist.net/anime/1/Cowboy_Bebop', 'MyAnimeList', '1', 'post'),
    ('https://anilist.co/user/AniList', 'AniList', 'AniList', 'profile'),
    ('https://anilist.co/anime/1/Cowboy-Bebop', 'AniList', '1', 'post'),
    ('https://anilist.co/activity/1', 'AniList', '1', 'post'),
    ('https://www.interpals.net/interpals', 'InterPals', 'interpals', 'profile'),
    ('https://www.livejournal.com/users/news', 'LiveJournal', 'news', 'profile'),
    ('https://www.livejournal.com/community/lj_releases', 'LiveJournal', 'lj_releases', 'group'),
    ('https://www.plurk.com/p/1', 'Plurk', '1', 'post'),
    ('https://www.plurk.com/plurk', 'Plurk', 'plurk', 'profile'),
    ('https://misskey.io/notes/abc', 'Misskey', 'abc', 'post'),
    ('https://misskey.io/@syuilo', 'Misskey', 'syuilo', 'profile'),
    ('https://njump.me/note1abc', 'Nostr', 'note1abc', 'post'),
    ('https://njump.me/npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6', 'Nostr', 'npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6', 'profile'),
    ('https://micro.blog/manton/1', 'Micro.blog', 'manton', 'post'),
    ('https://micro.blog/manton', 'Micro.blog', 'manton', 'profile'),
    ('https://vimeo.com/76979871', 'Vimeo', '76979871', 'video'),
    ('https://vimeo.com/staff', 'Vimeo', 'staff', 'profile'),
    ('https://www.patreon.com/posts/hello-1', 'Patreon', 'hello-1', 'post'),
    ('https://www.patreon.com/patreon', 'Patreon', 'patreon', 'profile'),
    ('https://linktr.ee/linktree', 'Linktree', 'linktree', 'profile'),
    ('https://about.me/tony', 'About.me', 'tony', 'profile'),
    ('https://gravatar.com/beau', 'Gravatar', 'beau', 'profile'),
    ('https://keybase.io/chris', 'Keybase', 'chris', 'profile'),
    ('https://hub.docker.com/u/library', 'Docker Hub', 'library', 'profile'),
    ('https://hub.docker.com/r/library/nginx', 'Docker Hub', 'library', 'repo'),
    ('https://hub.docker.com/_/nginx', 'Docker Hub', 'nginx', 'repo'),
    ('https://codepen.io/chriscoyier/pen/abc', 'CodePen', 'chriscoyier', 'post'),
    ('https://codepen.io/chriscoyier', 'CodePen', 'chriscoyier', 'profile'),
    ('https://www.chess.com/member/hikaru', 'Chess.com', 'hikaru', 'profile'),
    ('https://www.chess.com/club/chess-com-official', 'Chess.com', 'chess-com-official', 'group'),
    ('https://lichess.org/@/thibault', 'Lichess', 'thibault', 'profile'),
    ('https://lichess.org/team/lichess-swiss', 'Lichess', 'lichess-swiss', 'group'),
    ('https://www.speedrun.com/users/Pac', 'Speedrun.com', 'Pac', 'profile'),
    ('https://www.dailymotion.com/video/x8abcde', 'Dailymotion', 'x8abcde', 'video'),
    ('https://www.dailymotion.com/dailymotion', 'Dailymotion', 'dailymotion', 'profile'),
    ('https://giphy.com/gifs/hello-abc123', 'GIPHY', 'hello-abc123', 'post'),
    ('https://giphy.com/giphy', 'GIPHY', 'giphy', 'profile'),
    ('https://unsplash.com/photos/abc123', 'Unsplash', 'abc123', 'post'),
    ('https://unsplash.com/@unsplash', 'Unsplash', 'unsplash', 'profile'),
    ('https://www.pexels.com/photo/hello-1', 'Pexels', 'hello-1', 'post'),
    ('https://www.pexels.com/@pexels', 'Pexels', 'pexels', 'profile'),
    ('https://en.wikipedia.org/wiki/User:Jimbo_Wales', 'Wikipedia', 'Jimbo_Wales', 'profile'),
    ('https://en.wikipedia.org/wiki/Python_(programming_language)', 'Wikipedia', 'Python_(programming_language)', 'page'),
    ('https://www.xing.com/profile/Lars_Hinrichs', 'XING', 'Lars_Hinrichs', 'profile'),
    ('https://www.xing.com/pages/xing', 'XING', 'xing', 'page'),
    ('https://wellfound.com/u/naval', 'Wellfound', 'naval', 'profile'),
    ('https://wellfound.com/company/wellfound', 'Wellfound', 'wellfound', 'page'),
    ('https://habr.com/ru/users/alizar/', 'Habr', 'alizar', 'profile'),
    ('https://habr.com/ru/articles/1/', 'Habr', '1', 'post'),
    ('https://habr.com/ru/companies/habr/', 'Habr', 'habr', 'page'),
    ('https://pikabu.ru/@admin', 'Pikabu', 'admin', 'profile'),
    ('https://pikabu.ru/story/hello_1', 'Pikabu', 'hello_1', 'post'),
    ('https://pikabu.ru/community/it', 'Pikabu', 'it', 'group'),
    ('https://wordpress.com/en.blog', 'WordPress.com', 'en.blog', 'profile'),
    ('https://www.mixcloud.com/NTSRadio/hello-1/', 'Mixcloud', 'NTSRadio', 'post'),
    ('https://www.mixcloud.com/NTSRadio/', 'Mixcloud', 'NTSRadio', 'profile'),
    ('https://itch.io/profile/finji', 'itch.io', 'finji', 'profile'),
    ('https://namemc.com/profile/Notch', 'Minecraft', 'Notch', 'profile'),
    ('https://osu.ppy.sh/users/peppy', 'osu!', 'peppy', 'profile'),
    ('https://osu.ppy.sh/beatmapsets/1', 'osu!', '1', 'post'),
    ('https://codeforces.com/profile/tourist', 'Codeforces', 'tourist', 'profile'),
    ('https://leetcode.com/u/neal_wu/', 'LeetCode', 'neal_wu', 'profile'),
    ('https://leetcode.com/problems/two-sum/', 'LeetCode', 'two-sum', 'question'),
    ('https://leetcode.com/neal_wu', 'LeetCode', 'neal_wu', 'profile'),
    ('https://www.hackerrank.com/profile/shashank21j', 'HackerRank', 'shashank21j', 'profile'),
    ('https://www.codewars.com/users/jhoffner', 'Codewars', 'jhoffner', 'profile'),
    ('https://www.kaggle.com/datasets/kaggle/hello', 'Kaggle', 'kaggle', 'post'),
    ('https://www.kaggle.com/abhishek', 'Kaggle', 'abhishek', 'profile'),
    ('https://crates.io/users/dtolnay', 'crates.io', 'dtolnay', 'profile'),
    ('https://crates.io/crates/serde', 'crates.io', 'serde', 'repo'),
    ('https://dev.to/ben/hello-1abc', 'DEV Community', 'ben', 'post'),
    ('https://dev.to/ben', 'DEV Community', 'ben', 'profile'),
    ('https://hashnode.com/@hashnode', 'Hashnode', 'hashnode', 'profile'),
    ('https://gumroad.com/l/hello', 'Gumroad', 'hello', 'post'),
    ('https://gumroad.com/sahil', 'Gumroad', 'sahil', 'profile'),
    ('https://www.redbubble.com/people/redbubble/shop', 'Redbubble', 'redbubble', 'profile'),
    ('https://www.redbubble.com/i/sticker/hello-by-x/1.abc', 'Redbubble', 'hello-by-x', 'post'),
    ('https://kitsu.io/users/josh', 'Kitsu', 'josh', 'profile'),
    ('https://kitsu.io/anime/cowboy-bebop', 'Kitsu', 'cowboy-bebop', 'post'),
    ('https://rubygems.org/profiles/dhh', 'RubyGems', 'dhh', 'profile'),
    ('https://rubygems.org/gems/rails', 'RubyGems', 'rails', 'repo'),
    ('https://scratch.mit.edu/users/griffpatch/', 'Scratch', 'griffpatch', 'profile'),
    ('https://scratch.mit.edu/projects/1/', 'Scratch', '1', 'post'),
    ('https://scratch.mit.edu/studios/1/', 'Scratch', '1', 'group'),
    ('https://www.houzz.com/user/houzz', 'Houzz', 'houzz', 'profile'),
    ('https://www.houzz.com/pro/houzz', 'Houzz', 'houzz', 'page'),
    ('https://www.smule.com/recording/hello/1', 'Smule', 'hello', 'post'),
    ('https://www.smule.com/smule', 'Smule', 'smule', 'profile'),
    ('https://www.notion.so/@notion', 'Notion', 'notion', 'profile'),
    ('https://tellonym.me/tellonym', 'Tellonym', 'tellonym', 'profile'),
    ('https://www.bigo.tv/user/bigolive', 'BIGO LIVE', 'bigolive', 'profile'),
    ('https://www.ebay.com/usr/ebay', 'eBay', 'ebay', 'profile'),
    ('https://www.ebay.com/itm/123456789012', 'eBay', '123456789012', 'post'),
    ('https://www.ebay.com/str/ebay', 'eBay', 'ebay', 'page'),
    ('https://www.slideshare.net/slideshare/hello-1', 'SlideShare', 'slideshare', 'post'),
    ('https://www.slideshare.net/slideshare', 'SlideShare', 'slideshare', 'profile'),
    ('https://audiomack.com/audiomack/song/hello', 'Audiomack', 'audiomack', 'post'),
    ('https://audiomack.com/audiomack', 'Audiomack', 'audiomack', 'profile'),
    ('https://beacons.ai/beacons', 'Beacons', 'beacons', 'profile'),
    ('https://open.spotify.com/user/spotify', 'Spotify', 'spotify', 'profile'),
    ('https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU', 'Spotify', '4gzpq5DPGxSnKTe4SA8HAU', 'page'),
    ('https://open.spotify.com/track/4uLU6hMCjMI75M1A2tKUQC', 'Spotify', '4uLU6hMCjMI75M1A2tKUQC', 'post'),
    ('https://trakt.tv/users/justin', 'Trakt', 'justin', 'profile'),
    ('https://trakt.tv/movies/parasite-2019', 'Trakt', 'parasite-2019', 'post'),
    ('https://onlyfans.com/onlyfans', 'OnlyFans', 'onlyfans', 'profile'),
    ('https://www.figma.com/@figma', 'Figma', 'figma', 'profile'),
    ('https://www.figma.com/community/file/1', 'Figma', '1', 'post'),
    ('https://www.figma.com/design/abc/Hello', 'Figma', 'abc', 'post'),
    ('https://www.bitchute.com/channel/bitchute/', 'BitChute', 'bitchute', 'profile'),
    ('https://www.bitchute.com/video/abc123/', 'BitChute', 'abc123', 'video'),
    ('https://stratechery.substack.com', 'Substack', 'stratechery', 'page'),
    ('https://harrypotter.fandom.com', 'Fandom', 'harrypotter', 'group'),
    ('https://sufjanstevens.bandcamp.com', 'Bandcamp', 'sufjanstevens', 'profile'),
    ('https://news.livejournal.com', 'LiveJournal', 'news', 'profile'),
    ('https://manton.micro.blog', 'Micro.blog', 'manton', 'profile'),
    ('https://ucla.academia.edu', 'Academia.edu', 'ucla', 'page'),
    ('https://unix.stackexchange.com', 'Stack Exchange', 'unix', 'group'),
    ('https://en.blog.wordpress.com', 'WordPress.com', 'en.blog', 'profile'),
    ('https://finji.itch.io', 'itch.io', 'finji', 'profile'),
    ('https://sahil.gumroad.com', 'Gumroad', 'sahil', 'profile'),
    ('https://the-story.medium.com', 'Medium', 'the-story', 'page'),
    ('https://www.deviantart.com/deviantart/art/1', 'DeviantArt', 'deviantart', 'post'),
    ('https://www.deviantart.com/deviantart', 'DeviantArt', 'deviantart', 'profile'),
    ('https://www.douyin.com/user/MS4wLjABAAAA', 'Douyin', 'MS4wLjABAAAA', 'profile'),
    ('https://www.douyin.com/video/7000000000000000000', 'Douyin', '7000000000000000000', 'video'),
    ('https://500px.com/photo/1/hello', '500px', '1', 'post'),
    ('https://500px.com/p/500px', '500px', '500px', 'profile'),
    ('https://gab.com/gab/posts/1', 'Gab', 'gab', 'post'),
    ('https://gab.com/groups/1', 'Gab', '1', 'group'),
    ('https://gab.com/gab', 'Gab', 'gab', 'profile'),
    ('https://gettr.com/post/p1', 'GETTR', 'p1', 'post'),
    ('https://gettr.com/user/gettr', 'GETTR', 'gettr', 'profile'),
    ('https://www.kuaishou.com/profile/3xabc', 'Kuaishou', '3xabc', 'profile'),
    ('https://www.kuaishou.com/short-video/3xabc', 'Kuaishou', '3xabc', 'video'),
    ('https://www.minds.com/newsfeed/1', 'Minds', '1', 'post'),
    ('https://www.minds.com/groups/profile/1', 'Minds', '1', 'group'),
    ('https://www.minds.com/minds', 'Minds', 'minds', 'profile'),
    ('https://parler.com/feed/1', 'Parler', '1', 'post'),
    ('https://parler.com/parler', 'Parler', 'parler', 'profile'),
    ('https://www.pixiv.net/artworks/1', 'Pixiv', '1', 'post'),
    ('https://www.pixiv.net/users/11', 'Pixiv', '11', 'profile'),
    ('https://www.researchgate.net/profile/Albert-Einstein', 'ResearchGate', 'Albert-Einstein', 'profile'),
    ('https://www.researchgate.net/publication/1_Hello', 'ResearchGate', '1_Hello', 'post'),
    ('https://soundcloud.com/soundcloud/sets/hello', 'SoundCloud', 'soundcloud', 'post'),
    ('https://soundcloud.com/soundcloud/hello', 'SoundCloud', 'soundcloud', 'post'),
    ('https://soundcloud.com/soundcloud', 'SoundCloud', 'soundcloud', 'profile'),
    ('https://www.strava.com/athletes/1', 'Strava', '1', 'profile'),
    ('https://www.strava.com/clubs/strava', 'Strava', 'strava', 'group'),
    ('https://www.strava.com/activities/1', 'Strava', '1', 'post'),
    ('https://t.me/s/telegram', 'Telegram', 'telegram', 'channel'),
    ('https://t.me/joinchat/AAAAAEkk2WdoDrB4-Q8-gg', 'Telegram', 'AAAAAEkk2WdoDrB4-Q8-gg', 'group'),
    ('https://t.me/telegram/1', 'Telegram', 'telegram', 'post'),
    ('https://t.me/telegram', 'Telegram', 'telegram', 'profile'),
    ('https://truthsocial.com/@realDonaldTrump/posts/1', 'Truth Social', 'realDonaldTrump', 'post'),
    ('https://truthsocial.com/@realDonaldTrump', 'Truth Social', 'realDonaldTrump', 'profile'),
    ('https://www.tumblr.com/staff/1', 'Tumblr', 'staff', 'post'),
    ('https://www.tumblr.com/staff', 'Tumblr', 'staff', 'profile'),
    ('https://vk.com/wall1_1', 'VK', '1_1', 'post'),
    ('https://vk.com/club1', 'VK', '1', 'group'),
    ('https://vk.com/video-1_1', 'VK', '-1_1', 'video'),
    ('https://vk.com/durov', 'VK', 'durov', 'profile'),
    ('https://www.wattpad.com/user/Wattpad', 'Wattpad', 'Wattpad', 'profile'),
    ('https://www.wattpad.com/story/1-hello', 'Wattpad', '1', 'post'),
    ('https://www.wattpad.com/1-hello', 'Wattpad', '1', 'post'),
    ('https://weibo.com/u/1618051664', 'Weibo', '1618051664', 'profile'),
    ('https://weibo.com/1618051664/ABCDEF', 'Weibo', '1618051664', 'post'),
    ('https://weibo.com/xinhuanet', 'Weibo', 'xinhuanet', 'profile'),
    ('https://www.xiaohongshu.com/user/profile/5ff0e6410000000001000000', 'Xiaohongshu', '5ff0e6410000000001000000', 'profile'),
    ('https://www.xiaohongshu.com/explore/64abc', 'Xiaohongshu', '64abc', 'post'),
    ('https://www.zhihu.com/people/zhang-jia-wei', 'Zhihu', 'zhang-jia-wei', 'profile'),
    ('https://www.zhihu.com/question/19550225', 'Zhihu', '19550225', 'question'),
    ('https://www.zhihu.com/column/zhihuadmin', 'Zhihu', 'zhihuadmin', 'page'),
    ('https://www.linkedin.com/in/williamhgates', 'LinkedIn', 'williamhgates', 'profile'),
    ('https://www.linkedin.com/company/microsoft', 'LinkedIn', 'microsoft', 'page'),
    ('https://www.linkedin.com/groups/12345', 'LinkedIn', '12345', 'group'),
    ('https://www.linkedin.com/posts/linkedin_hello-activity-1', 'LinkedIn', 'linkedin_hello-activity-1', 'post'),
    ('https://www.snapchat.com/add/team.snapchat', 'Snapchat', 'team.snapchat', 'profile'),
    ('https://staff.tumblr.com', 'Tumblr', 'staff', 'profile'),
    ('https://imo.im/imo', 'imo', 'imo', 'profile'),
    ('https://line.me/ti/p/@linenews', 'LINE', 'linenews', 'profile'),
    ('https://line.me/R/ti/g/AbCdEf', 'LINE', 'AbCdEf', 'group'),
    ('https://m.me/facebook', 'Messenger', 'facebook', 'profile'),
    ('https://cafe.naver.com/joonggonara/1', 'Naver Cafe', 'joonggonara', 'post'),
    ('https://cafe.naver.com/joonggonara', 'Naver Cafe', 'joonggonara', 'group'),
    ('https://user.qzone.qq.com/10001', 'QQ', '10001', 'profile'),
    ('https://invite.viber.com/?g2=AbCdEf123', 'Viber', 'AbCdEf123', 'group'),
    ('https://u.wechat.com/MHzXqvUxQyv', 'WeChat', 'MHzXqvUxQyv', 'profile'),
    ('https://yubo.live/yubo', 'Yubo', 'yubo', 'profile'),
    ('https://discord.com/users/80351110224678912', 'Discord', '80351110224678912', 'profile'),
    ('https://discord.gg/discord', 'Discord', 'discord', 'server'),
    ('https://wa.me/14155238886', 'WhatsApp', '14155238886', 'profile'),
    ('https://chat.whatsapp.com/ABCDEFGHIJKLMNOPQRSTUV', 'WhatsApp', 'ABCDEFGHIJKLMNOPQRSTUV', 'group'),
    ('https://profiles.wordpress.org/orionprobe', 'WordPressOrg', 'orionprobe', 'profile'),
    ('https://sourceforge.net/u/orionprobe/profile', 'SourceForge', 'orionprobe', 'profile'),
    ('https://orionprobe.blogspot.com', 'Blogger', 'orionprobe', 'profile'),
    ('https://www.blogger.com/profile/orionprobe', 'Blogger (blogger.com)', 'orionprobe', 'profile'),
    ('https://tripadvisor.com/members/orionprobe', 'TripAdvisor', 'orionprobe', 'profile'),
    ('https://myspace.com/orionprobe', 'Myspace', 'orionprobe', 'profile'),
    ('https://themeforest.net/user/orionprobe', 'ThemeForest', 'orionprobe', 'profile'),
    ('https://www.weforum.org/people/orionprobe', 'Weforum', 'orionprobe', 'profile'),
    ('https://www.freepik.com/author/orionprobe', 'Freepik', 'orionprobe', 'profile'),
    ('https://www.change.org/o/orionprobe', 'Change.org', 'orionprobe', 'profile'),
    ('https://orionprobe.slack.com', 'Slack', 'orionprobe', 'profile'),
    ('https://disqus.com/orionprobe', 'Disqus', 'orionprobe', 'profile'),
    ('https://www.npmjs.com/~orionprobe', 'NPM', 'orionprobe', 'profile'),
    ('https://www.digitalocean.com/community/users/orionprobe', 'DigitalOcean', 'orionprobe', 'profile'),
    ('https://www.instructables.com/member/orionprobe', 'Instructables', 'orionprobe', 'profile'),
    ('https://ameblo.jp/orionprobe', 'Ameblo', 'orionprobe', 'profile'),
    ('https://huggingface.co/orionprobe', 'HuggingFace', 'orionprobe', 'profile'),
    ('https://laracasts.com/@orionprobe', 'Laracast', 'orionprobe', 'profile'),
    ('https://bitbucket.org/orionprobe', 'BitBucket', 'orionprobe', 'profile'),
    ('https://upwork.com/fl/orionprobe', 'Upwork', 'orionprobe', 'profile'),
    ('https://www.istockphoto.com/ru/portfolio/orionprobe', 'iStock', 'orionprobe', 'profile'),
    ('https://pastebin.com/u/orionprobe', 'Pastebin', 'orionprobe', 'profile'),
    ('https://foursquare.com/orionprobe', 'Foursquare', 'orionprobe', 'profile'),
    ('https://www.discogs.com/user/orionprobe', 'Discogs', 'orionprobe', 'profile'),
    ('https://ko-fi.com/orionprobe', 'kofi', 'orionprobe', 'profile'),
    ('https://www.rottentomatoes.com/critic/orionprobe/movies', 'Rottentomatoes', 'orionprobe', 'profile'),
    ('https://orionprobe.smugmug.com', 'Smugmug', 'orionprobe', 'profile'),
    ('https://www.duolingo.com/profile/orionprobe', 'Duolingo', 'orionprobe', 'profile'),
    ('https://www.ustream.tv/channel/adamorionprobe', 'Ustream', 'orionprobe', 'profile'),
    ('https://www.wikidot.com/user:info/orionprobe', 'Wikidot', 'orionprobe', 'profile'),
    ('https://imageshack.com/user/orionprobe', 'ImageShack', 'orionprobe', 'profile'),
    ('https://buymeacoff.ee/orionprobe', 'BuyMeACoffee', 'orionprobe', 'profile'),
    ('https://gitea.com/orionprobe', 'Gitea', 'orionprobe', 'profile'),
    ('https://genius.com/orionprobe', 'Genius', 'orionprobe', 'profile'),
    ('https://hubpages.com/@orionprobe', 'HubPages', 'orionprobe', 'profile'),
    ('https://pbase.com/orionprobe/profile', 'Pbase', 'orionprobe', 'profile'),
    ('https://auth.geeksforgeeks.org/user/orionprobe', 'Geeksfor Geeks', 'orionprobe', 'profile'),
    ('https://codeberg.org/orionprobe', 'codeberg.org', 'orionprobe', 'profile'),
    ('https://www.allrecipes.com/cook/orionprobe', 'AllRecipes', 'orionprobe', 'profile'),
    ('https://codecanyon.net/user/orionprobe', 'Codecanyon', 'orionprobe', 'profile'),
    ('https://www.codecademy.com/profiles/orionprobe', 'Codecademy', 'orionprobe', 'profile'),
    ('https://www.polygon.com/users/orionprobe', 'Polygon', 'orionprobe', 'profile'),
    ('https://forums.pcgamer.com/members?username=orionprobe', 'PCGamer', 'orionprobe', 'profile'),
    ('https://www.dreamstime.com/orionprobe_info', 'Dreamstime', 'orionprobe', 'profile'),
    ('https://speakerdeck.com/orionprobe', 'Speakerdeck', 'orionprobe', 'profile'),
    ('https://help.nextcloud.com/u/orionprobe/summary', 'Nextcloud Forum', 'orionprobe', 'profile'),
    ('https://max.ru/orionprobe', 'Max', 'orionprobe', 'profile'),
    ('https://tvtropes.org/pmwiki/pmwiki.php/Tropers/orionprobe', 'TVTropes', 'orionprobe', 'profile'),
    ('https://orionprobe.tistory.com', 'Tistory', 'orionprobe', 'profile'),
    ('https://jsfiddle.net/user/orionprobe', 'JSFiddle', 'orionprobe', 'profile'),
    ('https://www.gamesradar.com/uk/author/orionprobe', 'GamesRadar', 'orionprobe', 'profile'),
    ('https://www.geocaching.com/p?u=orionprobe', 'Geocaching', 'orionprobe', 'profile'),
    ('https://www.gog.com/u/orionprobe', 'Gog', 'orionprobe', 'profile'),
    ('https://coub.com/orionprobe', 'Coub', 'orionprobe', 'profile'),
    ('https://odysee.com/@orionprobe', 'Odysee', 'orionprobe', 'profile'),
    ('https://replit.com/@orionprobe', 'Replit', 'orionprobe', 'profile'),
    ('https://hackmd.io/@orionprobe', 'Hack MD', 'orionprobe', 'profile'),
    ('https://www.inaturalist.org/lists/orionprobe', 'iNaturalist', 'orionprobe', 'profile'),
    ('https://www.templatemonster.com/authors/orionprobe', 'TemplateMonster', 'orionprobe', 'profile'),
    ('https://teletype.in/@orionprobe', 'Teletype', 'orionprobe', 'profile'),
    ('https://ctan.org/author/orionprobe', 'CTAN', 'orionprobe', 'profile'),
    ('https://opencollective.com/orionprobe', 'OpenCollective', 'orionprobe', 'profile'),
    ('https://www.giantbomb.com/profile/orionprobe', 'Giantbomb', 'orionprobe', 'profile'),
    ('https://orionprobe.jalbum.net', 'jAlbum.net', 'orionprobe', 'profile'),
    ('https://orionprobe.newgrounds.com', 'Newgrounds', 'orionprobe', 'profile'),
    ('https://slides.com/orionprobe', 'Slides', 'orionprobe', 'profile'),
    ('https://ultimate-guitar.com/u/orionprobe', 'Ultimate-Guitar', 'orionprobe', 'profile'),
    ('https://orionprobe.contently.com', 'Contently', 'orionprobe', 'profile'),
    ('https://creativemarket.com/users/orionprobe', 'CreativeMarket', 'orionprobe', 'profile'),
    ('https://opensource.com/users/orionprobe', 'OpenSource', 'orionprobe', 'profile'),
    ('https://imgflip.com/user/orionprobe', 'Imgflip', 'orionprobe', 'profile'),
    ('https://hackaday.io/orionprobe', 'Hackaday', 'orionprobe', 'profile'),
    ('https://www.fodors.com/community/profile/orionprobe/forum-activity', 'Fodors', 'orionprobe', 'profile'),
    ('https://99designs.com/profiles/orionprobe', 'Designs99', 'orionprobe', 'profile'),
    ('https://www.pscp.tv/orionprobe', 'Periscope', 'orionprobe', 'profile'),
    ('https://freesound.org/people/orionprobe', 'Freesound', 'orionprobe', 'profile'),
    ('https://www.metal-archives.com/users/orionprobe', 'Metal-archives', 'orionprobe', 'profile'),
    ('https://www.kongregate.com/accounts/orionprobe', 'Kongregate', 'orionprobe', 'profile'),
    ('https://www.soup.io/author/orionprobe', 'Soup', 'orionprobe', 'profile'),
    ('https://www.furaffinity.net/gallery/orionprobe', 'Fur Affinity', 'orionprobe', 'profile'),
    ('https://www.itemfix.com/c/orionprobe', 'ItemFix', 'orionprobe', 'profile'),
    ('https://www.nintendolife.com/users/orionprobe', 'Nintendo Life', 'orionprobe', 'profile'),
    ('https://orionprobe.carbonmade.com', 'Carbonmade', 'orionprobe', 'profile'),
    ('https://www.moddb.com/members/orionprobe', 'ModDB', 'orionprobe', 'profile'),
    ('https://audiojungle.net/user/orionprobe', 'Audiojungle', 'orionprobe', 'profile'),
    ('https://www.tinder.com/@orionprobe', 'Tinder', 'orionprobe', 'profile'),
    ('https://www.domestika.org/orionprobe', 'domestika.org', 'orionprobe', 'profile'),
    ('https://noblogs.org/members/orionprobe', 'Noblogs', 'orionprobe', 'profile'),
    ('https://www.setlist.fm/user/orionprobe', 'Setlist', 'orionprobe', 'profile'),
    ('https://robertsspaceindustries.com/citizens/orionprobe', 'Star Citizen', 'orionprobe', 'profile'),
    ('https://robertsspaceindustries.com/community-hub/user/orionprobe', 'Star Citizen', 'orionprobe', 'profile'),
    ('https://www.jigsawplanet.com/orionprobe', 'Jigsawplanet', 'orionprobe', 'profile'),
    ('https://www.gaiaonline.com/profiles/orionprobe', 'GaiaOnline', 'orionprobe', 'profile'),
    ('https://www.memrise.com/user/orionprobe', 'Memrise', 'orionprobe', 'profile'),
    ('https://archiveofourown.org/users/orionprobe', 'ArchiveOfOurOwn', 'orionprobe', 'profile'),
    ('https://www.planetminecraft.com/member/orionprobe', 'PlanetMinecraft', 'orionprobe', 'profile'),
    ('https://musescore.com/orionprobe', 'Muse Score', 'orionprobe', 'profile'),
    ('https://www.theodysseyonline.com/user/@orionprobe', 'TheOdysseyOnline', 'orionprobe', 'profile'),
    ('https://www.sports.ru/profile/orionprobe', 'sports.ru', 'orionprobe', 'profile'),
    ('https://picsart.com/u/orionprobe', 'Picsart', 'orionprobe', 'profile'),
    ('https://www.wowhead.com/user=orionprobe', 'Wowhead', 'orionprobe', 'profile'),
    ('https://armorgames.com/user/orionprobe', 'Armorgames', 'orionprobe', 'profile'),
    ('https://members.fotki.com/orionprobe/about', 'Fotki', 'orionprobe', 'profile'),
    ('https://www.paltalk.com/people/users/orionprobe', 'Paltalk', 'orionprobe', 'profile'),
    ('https://videohive.net/user/orionprobe', 'VideoHive', 'orionprobe', 'profile'),
    ('https://www.clubhouse.com/@orionprobe', 'Clubhouse', 'orionprobe', 'profile'),
    ('https://www.proza.ru/avtor/orionprobe', 'Proza.ru', 'orionprobe', 'profile'),
    ('https://www.namepros.com/members?username=orionprobe', 'Namepros', 'orionprobe', 'profile'),
    ('https://write.as/orionprobe', 'write.as', 'orionprobe', 'profile'),
    ('https://www.warriorforum.com/members/orionprobe.html', 'Warrior Forum', 'orionprobe', 'profile'),
    ('https://www.are.na/orionprobe', 'are.na', 'orionprobe', 'profile'),
    ('https://www.wykop.pl/ludzie/orionprobe', 'Wykop', 'orionprobe', 'profile'),
    ('https://www.residentadvisor.net/profile/orionprobe', 'ResidentAdvisor', 'orionprobe', 'profile'),
    ('https://www.sporcle.com/user/orionprobe/people', 'Sporcle', 'orionprobe', 'profile'),
    ('https://teamtreehouse.com/profiles/orionprobe', 'Treehouse', 'orionprobe', 'profile'),
    ('https://www.coroflot.com/orionprobe', 'Coroflot', 'orionprobe', 'profile'),
    ('https://www.jeuxvideo.com/profil/orionprobe?mode=infos', 'JeuxVideo', 'orionprobe', 'profile'),
    ('https://www.stihi.ru/avtor/orionprobe', 'Stihi.ru', 'orionprobe', 'profile'),
    ('https://orionprobe.exposure.co', 'Exposure', 'orionprobe', 'profile'),
    ('https://lyricstranslate.com/sco/translator/orionprobe', 'LyricsTranslate', 'orionprobe', 'profile'),
    ('https://www.guru.com/freelancers/orionprobe', 'Guru', 'orionprobe', 'profile'),
    ('https://www.gutefrage.net/nutzer/orionprobe', 'Gutefrage', 'orionprobe', 'profile'),
    ('https://coderwall.com/orionprobe', 'Coderwall', 'orionprobe', 'profile'),
    ('https://observablehq.com/@orionprobe', 'Observable', 'orionprobe', 'profile'),
    ('https://www.pushsquare.com/users/orionprobe', 'PushSquare', 'orionprobe', 'profile'),
    ('https://www.codementor.io/orionprobe', 'Codementor', 'orionprobe', 'profile'),
    ('https://n4g.com/user/home/orionprobe', 'N4g', 'orionprobe', 'profile'),
    ('https://www.lomography.com/homes/orionprobe', 'Lomography', 'orionprobe', 'profile'),
    ('https://pixelfed.social/orionprobe', 'pixelfed.social', 'orionprobe', 'profile'),
    ('https://www.neoseeker.com/members/orionprobe', 'Neoseeker', 'orionprobe', 'profile'),
    ('https://www.sythe.org/members?username=orionprobe', 'Sythe', 'orionprobe', 'profile'),
    ('https://www.filmweb.pl/user/orionprobe', 'FilmWeb', 'orionprobe', 'profile'),
    ('https://orionprobe.listal.com', 'Listal', 'orionprobe', 'profile'),
    ('https://www.spatial.io/@orionprobe', 'Spatial', 'orionprobe', 'profile'),
    ('https://paragraph.com/@orionprobe', 'Paragraph', 'orionprobe', 'profile'),
    ('https://notabug.org/orionprobe', 'notabug.org', 'orionprobe', 'profile'),
    ('https://www.mydramalist.com/profile/orionprobe', 'Mydramalist', 'orionprobe', 'profile'),
    ('https://www.pinkbike.com/u/orionprobe', 'Pinkbike', 'orionprobe', 'profile'),
    ('https://thechive.com/author/orionprobe', 'Thechive', 'orionprobe', 'profile'),
    ('https://www.goldderby.com/members/orionprobe', 'Goldderby', 'orionprobe', 'profile'),
    ('https://www.meetme.com/orionprobe', 'MeetMe', 'orionprobe', 'profile'),
    ('https://www.flyertalk.com/forum/members/orionprobe.html', 'Flyertalk', 'orionprobe', 'profile'),
    ('https://gbatemp.net/members?username=orionprobe', 'GBAtemp.net', 'orionprobe', 'profile'),
    ('https://www.brusheezy.com/members/orionprobe', 'Brusheezy', 'orionprobe', 'profile'),
    ('https://www.avforums.com/members?username=orionprobe', 'Avforums', 'orionprobe', 'profile'),
    ('https://www.mobypicture.com/user/orionprobe', 'Mobypicture', 'orionprobe', 'profile'),
    ('https://dlive.tv/orionprobe', 'DLive', 'orionprobe', 'profile'),
    ('https://www.trueachievements.com/gamer/orionprobe', 'TrueAchievements', 'orionprobe', 'profile'),
    ('https://www.physicsforums.com/members?username=orionprobe', 'Physicsforums', 'orionprobe', 'profile'),
    ('https://opengameart.org/users/orionprobe', 'Open Game Art', 'orionprobe', 'profile'),
    ('https://lobste.rs/u/orionprobe', 'Lobsters', 'orionprobe', 'profile'),
    ('https://www.ifunny.co/user/orionprobe', 'iFunny', 'orionprobe', 'profile'),
    ('https://profiles.topcoder.com/orionprobe', 'Topcoder', 'orionprobe', 'profile'),
    ('https://orionprobe.picturepush.com', 'picturepush.com', 'orionprobe', 'profile'),
    ('https://www.voices.com/actors/orionprobe', 'Voices', 'orionprobe', 'profile'),
    ('https://www.nhattao.com/members?username=orionprobe', 'nhattao.com', 'orionprobe', 'profile'),
    ('https://repl.it/@orionprobe', 'Repl.it', 'orionprobe', 'profile'),
    ('https://orionprobe.portfoliobox.net', '{username}.portfoliobox.net', 'orionprobe', 'profile'),
    ('https://gallog.dcinside.com/orionprobe', 'Dcinside', 'orionprobe', 'profile'),
    ('https://www.digitalpoint.com/members?username=orionprobe', 'DigitalPoint', 'orionprobe', 'profile'),
    ('https://asciinema.org/~orionprobe', 'Asciinema', 'orionprobe', 'profile'),
    ('https://www.cfd-online.com/Forums/members/orionprobe.html', 'cfd-online', 'orionprobe', 'profile'),
    ('https://funnyjunk.com/user/orionprobe', 'Funnyjunk', 'orionprobe', 'profile'),
    ('https://gloria.tv/orionprobe', 'gloria.tv', 'orionprobe', 'profile'),
    ('https://ficwad.com/a/orionprobe/favorites/authors', 'Ficwad', 'orionprobe', 'profile'),
    ('https://www.tripline.net/orionprobe', 'Tripline', 'orionprobe', 'profile'),
    ('https://deepdreamgenerator.com/u/orionprobe', 'DeepDreamGenerator', 'orionprobe', 'profile'),
    ('https://1x.com/orionprobe', '1x', 'orionprobe', 'profile'),
    ('https://www.pokecommunity.com/members?username=orionprobe', 'Pokecommunity', 'orionprobe', 'profile'),
    ('https://samlib.ru/e/orionprobe', 'Samlib', 'orionprobe', 'profile'),
    ('https://goodgame.ru/channel/orionprobe', 'goodgame.ru', 'orionprobe', 'profile'),
    ('https://www.pling.com/u/orionprobe', 'Pling', 'orionprobe', 'profile'),
    ('https://hardforum.com/members?username=orionprobe', 'Hardforum', 'orionprobe', 'profile'),
    ('https://www.23hq.com/orionprobe', '23hq', 'orionprobe', 'profile'),
    ('https://androidforums.com/members?username=orionprobe', 'Androidforums', 'orionprobe', 'profile'),
    ('https://www.comedy.co.uk/profile/orionprobe', 'Comedy', 'orionprobe', 'profile'),
    ('https://youpic.com/photographer/orionprobe', 'YouPic', 'orionprobe', 'profile'),
    ('https://polarsteps.com/orionprobe', 'Polarsteps', 'orionprobe', 'profile'),
    ('https://platzi.com/p/orionprobe', 'Platzi', 'orionprobe', 'profile'),
    ('https://www.writingforums.org/members?username=orionprobe', 'writingforums.org', 'orionprobe', 'profile'),
    ('https://profil.chatujme.cz/orionprobe', 'Chatujme.cz', 'orionprobe', 'profile'),
    ('https://www.antiquers.com/members?username=orionprobe', 'Antiquers', 'orionprobe', 'profile'),
    ('https://www.bigsoccer.com/members?username=orionprobe', 'Bigsoccer', 'orionprobe', 'profile'),
    ('https://skyblock.net/members?username=orionprobe', 'Skyblock', 'orionprobe', 'profile'),
    ('https://hive.blog/@orionprobe', 'Hive Blog', 'orionprobe', 'profile'),
    ('https://joyreactor.cc/user/orionprobe', 'joyreactor.cc', 'orionprobe', 'profile'),
    ('https://www.viewbug.com/member/orionprobe', 'ViewBug', 'orionprobe', 'profile'),
    ('https://www.exophase.com/user/orionprobe', 'Exophase', 'orionprobe', 'profile'),
    ('https://webdeveloper.com/u/orionprobe', 'webdeveloper.com', 'orionprobe', 'profile'),
    ('https://fediverse.party/en/orionprobe', 'fediverse.party', 'orionprobe', 'profile'),
    ('https://www.weblancer.net/users/orionprobe', 'Weblancer', 'orionprobe', 'profile'),
    ('https://sugoidesu.net/members?username=orionprobe', 'Sugoidesu', 'orionprobe', 'profile'),
    ('https://profi.ru/profile/orionprobe', 'profi.ru', 'orionprobe', 'profile'),
    ('https://thoughts.com/members/orionprobe', 'thoughts.com', 'orionprobe', 'profile'),
    ('https://www.gapyear.com/members/orionprobe', 'Gapyear', 'orionprobe', 'profile'),
    ('https://www.myinstants.com/profile/orionprobe', 'Myinstants', 'orionprobe', 'profile'),
    ('https://smokingmeatforums.com/members?username=orionprobe', 'smokingmeatforums.com', 'orionprobe', 'profile'),
    ('https://reibert.info/members?username=orionprobe', 'Reibert', 'orionprobe', 'profile'),
    ('https://freelancehunt.com/freelancer/orionprobe.html', 'Freelancehunt', 'orionprobe', 'profile'),
    ('https://atcoder.jp/users/orionprobe', 'Atcoder', 'orionprobe', 'profile'),
    ('https://www.jetpunk.com/users/orionprobe', 'Jetpunk', 'orionprobe', 'profile'),
    ('https://www.rappad.co/users/orionprobe', 'Rappad', 'orionprobe', 'profile'),
    ('https://nationstates.net/nation=orionprobe', 'NationStates Nation', 'orionprobe', 'profile'),
    ('https://ethresear.ch/u/orionprobe/summary', 'Ethresear', 'orionprobe', 'profile'),
    ('https://www.homebrewtalk.com/members?username=orionprobe', 'homebrewtalk.com', 'orionprobe', 'profile'),
    ('https://lemmy.world/u/orionprobe', 'Lemmy World', 'orionprobe', 'profile'),
    ('https://www.zoomit.ir/user/orionprobe', 'Zoomir.ir', 'orionprobe', 'profile'),
    ('https://beta.cent.co/@orionprobe', 'Cent', 'orionprobe', 'profile'),
    ('https://vjudge.net/user/orionprobe', 'Vjudge', 'orionprobe', 'profile'),
    ('https://www.thesimsresource.com/members/orionprobe', 'TheSimsResource', 'orionprobe', 'profile'),
    ('https://vgtimes.ru/games/orionprobe/forum', 'Vgtimes/Games', 'orionprobe', 'profile'),
    ('https://vgtimes.ru/user/orionprobe', 'Vgtimes/Games', 'orionprobe', 'profile'),
    ('https://windowsforum.com/members?username=orionprobe', 'Windowsforum', 'orionprobe', 'profile'),
    ('https://warpcast.com/orionprobe', 'Warpcast', 'orionprobe', 'profile'),
    ('https://topmate.io/orionprobe', 'Topmate', 'orionprobe', 'profile'),
    ('https://data.typeracer.com/pit/profile?user=orionprobe', 'Typeracer', 'orionprobe', 'profile'),
    ('https://devrant.com/users/orionprobe', 'devRant', 'orionprobe', 'profile'),
    ('https://rmmedia.ru/members?username=orionprobe', 'Rmmedia', 'orionprobe', 'profile'),
    ('https://www.hometheaterforum.com/community/members?username=orionprobe', 'Hometheaterforum', 'orionprobe', 'profile'),
    ('https://www.vlr.gg/user/orionprobe', 'VLR', 'orionprobe', 'profile'),
    ('https://www.hackingwithswift.com/users/orionprobe', 'HackingWithSwift', 'orionprobe', 'profile'),
    ('https://pokemonshowdown.com/users/orionprobe', 'Pokemon Showdown', 'orionprobe', 'profile'),
    ('https://mynickname.com/orionprobe', 'mynickname.com', 'orionprobe', 'profile'),
    ('https://ethereum-magicians.org/u/orionprobe/summary', 'Ethereum-magicians', 'orionprobe', 'profile'),
    ('https://www.govloop.com/members/orionprobe', 'Govloop', 'orionprobe', 'profile'),
    ('https://designspiration.com/orionprobe', 'Designspiration', 'orionprobe', 'profile'),
    ('https://www.politforums.net/free/profile.php?showuser=orionprobe', 'Politforums', 'orionprobe', 'profile'),
    ('https://www.icheckmovies.com/profiles/orionprobe', 'Icheckmovies', 'orionprobe', 'profile'),
    ('https://orionprobe.crevado.com', 'Crevado', 'orionprobe', 'profile'),
    ('https://monkeytype.com/profile/orionprobe', 'Monkeytype', 'orionprobe', 'profile'),
    ('https://e621.net/users/orionprobe', 'E621', 'orionprobe', 'profile'),
    ('https://gvectors.com/forum/profile/orionprobe', 'Gvectors', 'orionprobe', 'profile'),
    ('https://www.rollitup.org/members?username=orionprobe', 'Rollitup', 'orionprobe', 'profile'),
    ('https://rive.app/a/orionprobe', 'rive.app', 'orionprobe', 'profile'),
    ('https://mstdn.io/@orionprobe', 'mstdn.io', 'orionprobe', 'profile'),
    ('https://www.lightstalking.com/author/orionprobe', 'lightstalking.com', 'orionprobe', 'profile'),
    ('https://gurushots.com/orionprobe/photos', 'GuruShots', 'orionprobe', 'profile'),
    ('https://www.weasyl.com/~orionprobe', 'Weasyl', 'orionprobe', 'profile'),
    ('https://www.touristlink.com/user/orionprobe', 'Touristlink', 'orionprobe', 'profile'),
    ('https://www.w7forums.com/members?username=orionprobe', 'W7forums', 'orionprobe', 'profile'),
    ('https://fragment.com/username/orionprobe', 'Fragment', 'orionprobe', 'profile'),
    ('https://www.allthelyrics.com/forum/member.php?username=orionprobe', 'AllTheLyrics', 'orionprobe', 'profile'),
    ('https://nothing.community/u/orionprobe', 'Nothing Community', 'orionprobe', 'profile'),
    ('https://www.clozemaster.com/players/orionprobe', 'Clozemaster', 'orionprobe', 'profile'),
    ('https://999.md/ru/profile/orionprobe', '999.md', 'orionprobe', 'profile'),
    ('https://www.arrse.co.uk/community/members?username=orionprobe', 'Arrse', 'orionprobe', 'profile'),
    ('https://www.1001tracklists.com/user/orionprobe/index.html', '1001tracklists', 'orionprobe', 'profile'),
    ('https://www.livios.be/nl/forum/leden/orionprobe', 'Livios', 'orionprobe', 'profile'),
    ('https://pronouns.page/@orionprobe', 'Pronouns.page', 'orionprobe', 'profile'),
    ('https://au.ru/user/orionprobe', 'Au', 'orionprobe', 'profile'),
    ('https://listography.com/orionprobe', 'Listography', 'orionprobe', 'profile'),
    ('https://millerovo161.ru/index/8-0-orionprobe', 'millerovo161.ru', 'orionprobe', 'profile'),
    ('https://www.rlocman.ru/forum/member.php?username=orionprobe', 'Rlocman', 'orionprobe', 'profile'),
    ('https://orionprobe.aminus3.com', 'Aminus3', 'orionprobe', 'profile'),
    ('https://elixirforum.com/u/orionprobe/summary', 'Elixirforum', 'orionprobe', 'profile'),
    ('https://egpu.io/forums/profile/orionprobe', 'eGPU', 'orionprobe', 'profile'),
    ('https://vintage-mustang.com/members?username=orionprobe', 'vintage-mustang.com', 'orionprobe', 'profile'),
    ('https://www.forum.hr/member.php?username=orionprobe', 'forum.hr', 'orionprobe', 'profile'),
    ('https://school2dobrinka.ru/index/8-0-orionprobe', 'school2dobrinka.ru', 'orionprobe', 'profile'),
    ('https://www.jigidi.com/user/orionprobe', 'Jigidi', 'orionprobe', 'profile'),
    ('https://www.chemport.ru/forum/memberlist.php?username=orionprobe', 'Chemport', 'orionprobe', 'profile'),
    ('https://www.snbforums.com/members?username=orionprobe', 'Snbforums', 'orionprobe', 'profile'),
    ('https://www.redcafe.net/members?username=orionprobe', 'Redcafe', 'orionprobe', 'profile'),
    ('https://www.showme.com/orionprobe', 'Showme', 'orionprobe', 'profile'),
    ('https://www.office-forums.com/members?username=orionprobe', 'Office-forums', 'orionprobe', 'profile'),
    ('https://subaruoutback.org/members?username=orionprobe', 'subaruoutback.org', 'orionprobe', 'profile'),
    ('https://svtperformance.com/members?username=orionprobe', 'svtperformance.com', 'orionprobe', 'profile'),
    ('https://www.railforums.co.uk/members?username=orionprobe', 'railforums.co.uk', 'orionprobe', 'profile'),
    ('https://subaruforester.org/members?username=orionprobe', 'subaruforester.org', 'orionprobe', 'profile'),
    ('https://www.ruby-forum.com/u/orionprobe/summary', 'Ruby-forum', 'orionprobe', 'profile'),
    ('https://www.blipfoto.com/orionprobe', 'Blipfoto', 'orionprobe', 'profile'),
    ('https://www.nitrotype.com/racer/orionprobe', 'Nitro Type', 'orionprobe', 'profile'),
    ('https://www.blast.hk/members?username=orionprobe', 'Blast', 'orionprobe', 'profile'),
    ('https://vishivalochka.ru/index/8-0-orionprobe', 'vishivalochka.ru', 'orionprobe', 'profile'),
    ('https://cs-lords.ru/index/8-0-orionprobe', 'CS-Lords', 'orionprobe', 'profile'),
    ('https://niketalk.com/members?username=orionprobe', 'Niketalk', 'orionprobe', 'profile'),
    ('https://www.thefirearmsforum.com/members?username=orionprobe', 'Thefirearmsforum', 'orionprobe', 'profile'),
    ('https://www.affiliatefix.com/members?username=orionprobe', 'Affiliatefix', 'orionprobe', 'profile'),
    ('https://sigtalk.com/members?username=orionprobe', 'sigtalk.com', 'orionprobe', 'profile'),
    ('https://mir-stalkera.ru/index/8-0-orionprobe', 'mir-stalkera.ru', 'orionprobe', 'profile'),
    ('https://www.mac-help.com/members?username=orionprobe', 'Mac-help', 'orionprobe', 'profile'),
    ('https://www.flashflashrevolution.com/profile/orionprobe', 'Flashflashrevolution', 'orionprobe', 'profile'),
    ('https://dmoj.ca/user/orionprobe', 'DMOJ', 'orionprobe', 'profile'),
    ('https://www.lada-vesta.net/member.php?username=orionprobe', 'lada-vesta.net', 'orionprobe', 'profile'),
    ('https://sysadmins.ru/memberorionprobe.html', 'Sysadmins', 'orionprobe', 'profile'),
    ('https://jeepgarage.org/members?username=orionprobe', 'jeepgarage.org', 'orionprobe', 'profile'),
    ('https://4gameforum.com/members?username=orionprobe', '4gameforum', 'orionprobe', 'profile'),
    ('https://forum.spells8.com/u/orionprobe', 'Spells8', 'orionprobe', 'profile'),
    ('https://101010.pl/@orionprobe', '101010.pl', 'orionprobe', 'profile'),
    ('https://cryptohack.org/user/orionprobe', 'Crypto Hack', 'orionprobe', 'profile'),
    ('https://orionprobe.piccsy.com', 'Piccsy', 'orionprobe', 'profile'),
    ('https://www.windows10forums.com/members?username=orionprobe', 'Windows10forums', 'orionprobe', 'profile'),
    ('https://ifish.net/members?username=orionprobe', 'ifish.net', 'orionprobe', 'profile'),
    ('https://swedroid.se/forum/members?username=orionprobe', 'swedroid.se', 'orionprobe', 'profile'),
    ('https://cssbattle.dev/player/orionprobe', 'CSSBattle', 'orionprobe', 'profile'),
    ('https://macosx.com/members?username=orionprobe', 'Macosx', 'orionprobe', 'profile'),
    ('https://www.religiousforums.com/members?username=orionprobe', 'ReligiousForums', 'orionprobe', 'profile'),
    ('https://www.not606.com/members?username=orionprobe', 'not606.com', 'orionprobe', 'profile'),
    ('https://gpodder.net/user/orionprobe', 'Gpodder', 'orionprobe', 'profile'),
    ('https://forum.md/ru/users/orionprobe', 'md', 'orionprobe', 'profile'),
    ('https://www.imood.com/users/orionprobe', 'Imood', 'orionprobe', 'profile'),
    ('https://armtorg.ru/forum/memberlist.php?username=orionprobe', 'Armtorg', 'orionprobe', 'profile'),
    ('https://www.russpuss.ru/profile/orionprobe', 'russpuss.ru', 'orionprobe', 'profile'),
    ('https://v-twinforum.com/members?username=orionprobe', 'v-twinforum.com', 'orionprobe', 'profile'),
    ('https://fanficslandia.com/index.php/members?username=orionprobe', 'fanficslandia.com', 'orionprobe', 'profile'),
    ('https://www.qbn.com/orionprobe', 'Qbn', 'orionprobe', 'profile'),
    ('https://www.lkforum.ru/member.php?username=orionprobe', 'Lkforum', 'orionprobe', 'profile'),
    ('https://www.clubsnap.com/members?username=orionprobe', 'clubsnap.com', 'orionprobe', 'profile'),
    ('https://wolpy.com/orionprobe/profile', 'Wolpy', 'orionprobe', 'profile'),
    ('https://warframe.market/profile/orionprobe', 'Warframe Market', 'orionprobe', 'profile'),
    ('https://www.cubecraft.net/members?username=orionprobe', 'cubecraft.net', 'orionprobe', 'profile'),
    ('https://tv-games.ru/forum/member.php?username=orionprobe', 'Tv-games', 'orionprobe', 'profile'),
    ('https://sniperforums.com/members?username=orionprobe', 'sniperforums.com', 'orionprobe', 'profile'),
    ('https://izobil.ru/index/8-0-orionprobe', 'izobil.ru', 'orionprobe', 'profile'),
    ('https://goldroyal.net/member.php?username=orionprobe', 'Goldroyal', 'orionprobe', 'profile'),
    ('https://www.fcrubin.ru/forum/member.php?username=orionprobe', 'FCRubin', 'orionprobe', 'profile'),
    ('https://www.oakleyforum.com/members?username=orionprobe', 'oakleyforum.com', 'orionprobe', 'profile'),
    ('https://www.hunting.ru/forum/members?username=orionprobe', 'hunting', 'orionprobe', 'profile'),
    ('https://uvelir.net/member.php?username=orionprobe', 'Uvelir', 'orionprobe', 'profile'),
    ('https://www.thelion.com/bin/profile.cgi?c=s&ru_name=orionprobe', 'Thelion', 'orionprobe', 'profile'),
    ('https://www.xshaker.net/orionprobe.html', 'XShaker', 'orionprobe', 'profile'),
    ('https://www.nucastle.co.uk/members?username=orionprobe', 'nucastle.co.uk', 'orionprobe', 'profile'),
    ('https://www.realmeye.com/player/orionprobe', 'Realmeye', 'orionprobe', 'profile'),
    ('https://www.hitmanforum.com/u/orionprobe/summary', 'Hitmanforum', 'orionprobe', 'profile'),
    ('https://dating.ru/orionprobe', 'Dating.Ru', 'orionprobe', 'profile'),
    ('https://www.forum-volgograd.ru/members?username=orionprobe', 'Volgograd Forum', 'orionprobe', 'profile'),
    ('https://www.tigerfan.com/members?username=orionprobe', 'tigerfan.com', 'orionprobe', 'profile'),
    ('https://impalaforums.com/members?username=orionprobe', 'impalaforums.com', 'orionprobe', 'profile'),
    ('https://www.forumjizni.ru/member.php?username=orionprobe', 'ForumJizni', 'orionprobe', 'profile'),
    ('https://xgm.guru/user/orionprobe', 'xgm.guru', 'orionprobe', 'profile'),
    ('https://www.texasguntalk.com/members?username=orionprobe', 'Texasguntalk', 'orionprobe', 'profile'),
    ('https://www.politikforum.ru/member.php?username=orionprobe', 'Politikforum', 'orionprobe', 'profile'),
    ('https://truthbook.com/forum/memberlist.php?username=orionprobe', 'Truthbook', 'orionprobe', 'profile'),
    ('https://defenceforumindia.com/members?username=orionprobe', 'DefenceForumIndia', 'orionprobe', 'profile'),
    ('https://www.forumsdrom.ru/member.php?username=orionprobe', 'forums.drom.ru', 'orionprobe', 'profile'),
    ('https://www.antique-bottles.net/members?username=orionprobe', 'Antique-bottles', 'orionprobe', 'profile'),
    ('https://www.ridemonkey.com/members?username=orionprobe', 'ridemonkey.com', 'orionprobe', 'profile'),
    ('https://www.discussfastpitch.com/members?username=orionprobe', 'Discussfastpitch', 'orionprobe', 'profile'),
    ('https://avto-forum.name/members?username=orionprobe', 'Avto-forum.name', 'orionprobe', 'profile'),
    ('https://spaces.im/mysite/index/orionprobe', 'Spaces', 'orionprobe', 'profile'),
    ('https://www.russian.fi/forum/member.php?username=orionprobe', 'RussianFI', 'orionprobe', 'profile'),
    ('https://www.xtratime.org/members?username=orionprobe', 'xtratime.org', 'orionprobe', 'profile'),
    ('https://www.nikoncafe.com/members?username=orionprobe', 'nikoncafe.com', 'orionprobe', 'profile'),
    ('https://cowboyszone.com/members?username=orionprobe', 'cowboyszone.com', 'orionprobe', 'profile'),
    ('https://www.thebuddyforum.com/members?username=orionprobe', 'Thebuddyforum', 'orionprobe', 'profile'),
    ('https://www.vauxhallownersnetwork.co.uk/members?username=orionprobe', 'vauxhallownersnetwork.co.uk', 'orionprobe', 'profile'),
    ('https://erogen.club/members?username=orionprobe', 'Erogen.club', 'orionprobe', 'profile'),
    ('https://www.mineplex.com/members?username=orionprobe', 'mineplex.com', 'orionprobe', 'profile'),
    ('https://profile.codersrank.io/user/orionprobe', 'Coders Rank', 'orionprobe', 'profile'),
    ('https://worldofplayers.ru/members?username=orionprobe', 'Worldofplayers', 'orionprobe', 'profile'),
    ('https://namu.wiki/w/%EC%82%AC%EC%9A%A9%EC%9E%90:orionprobe', 'Namuwiki', 'orionprobe', 'profile'),
)


def test_every_route_case_resolves_to_the_expected_platform_identity_and_type() -> None:
    failures = []
    for url, name, identity, target in ROUTE_CASES:
        route = custom_recon._route(url)
        got = (route[0].constants.NAME, route[1], route[2]) if route else None
        if got != (name, identity, target):
            failures.append((url, got, (name, identity, target)))
    assert not failures, failures


def test_every_registered_platform_has_at_least_one_route_case() -> None:
    covered = {name for _url, name, _identity, _target in ROUTE_CASES}
    missing = [module.constants.NAME for module in registry.platforms.values() if module.constants.NAME not in covered]
    assert not missing, missing


def test_every_route_pattern_of_every_platform_is_exercised() -> None:
    hits: dict[tuple[str, str], int] = {}
    for url, name, _identity, _target in ROUTE_CASES:
        route = custom_recon._route(url)
        if route is None:
            continue
        module = route[0]
        parts = _parts(url)
        for pattern, target in getattr(module, "ROUTES", ()):
            if re.fullmatch(pattern, parts[0], flags=re.IGNORECASE) or re.fullmatch(pattern, parts[1], flags=re.IGNORECASE):
                hits[(module.constants.NAME, pattern)] = hits.get((module.constants.NAME, pattern), 0) + 1
                break
    missing = [
        (module.constants.NAME, pattern)
        for module in registry.platforms.values()
        for pattern, _target in getattr(module, "ROUTES", ())
        if (module.constants.NAME, pattern) not in hits
    ]
    assert not missing, missing


def test_every_supported_platform_passes_the_probe_contract() -> None:
    sample = ReconProbeConstants.SAMPLE_USERNAME
    failures = []
    for key, module in registry.platforms.items():
        constants = module.constants
        if getattr(constants, "CRAWL_TYPE", "normal") == "unverified":
            if not getattr(module, "ROUTES", ()) and not getattr(module, "SUBDOMAIN", None):
                failures.append((key, "unverified without ROUTES or SUBDOMAIN"))
            continue
        if not getattr(constants, "SUPPORTED", True):
            if not getattr(constants, "REASON", ""):
                failures.append((key, "unsupported without REASON"))
            continue
        try:
            assert re.fullmatch(constants.GRAMMAR, sample), "GRAMMAR rejects sample"
            probe = module.probe_url(sample)
            assert probe.startswith("https://"), "probe_url is not https"
            verdict = module.evaluate(0, "", probe)
            assert isinstance(verdict, tuple) and len(verdict) == 2, "evaluate contract"
            assert verdict[0] in ReconProbeConstants.VALID_VERDICTS, "invalid verdict"
        except Exception as exc:
            failures.append((key, f"{type(exc).__name__}: {exc}"))
    assert not failures, failures


def _parts(url: str) -> tuple[str, str]:
    from api.social_manager.social_recon.normalizer import normalizer

    _value, _host, path, query = normalizer.url(url)
    return path, f"{path}?{query}" if query else path


def test_unverified_platforms_route_without_probing_and_defer_to_maigret() -> None:
    from unittest.mock import patch

    from api.social_manager.social_recon.custom_recon.core import http_client

    with patch.object(http_client, "fetch") as fetch, patch.object(http_client, "browser_fetch") as browser, patch.object(http_client, "online_fetch") as online:
        route = custom_recon._route("https://discord.gg/discord")
        assert route and route[0].constants.NAME == "Discord" and route[1:3] == ("discord", "server")
        assert custom_recon.check("discord", "80351110224678912").verdict == "unknown"
        assert custom_recon.extract_url("https://discord.com/users/80351110224678912") is None
    assert not fetch.called and not browser.called and not online.called


CANONICAL_PROFILE_FIELDS = {"display_name", "description", "avatar", "cover", "followers", "following", "posts", "id", "created_at", "location", "website"}


def test_every_module_emits_only_canonical_profile_fields() -> None:
    import glob
    import os

    offenders = []
    for path in sorted(glob.glob(str(ReconProbeConstants.PLATFORM_ROOT / "*.py"))):
        source = open(path, encoding="utf-8").read()
        for block in re.finditer(r"info = \{(.*?)\n    \}", source, flags=re.DOTALL):
            for key in re.findall(r'^\s+"([a-z_]+)":', block.group(1), flags=re.M):
                if key not in CANONICAL_PROFILE_FIELDS:
                    offenders.append((os.path.basename(path), key))
        if "info.update(parse.counts" in source:
            offenders.append((os.path.basename(path), "raw parse.counts"))
    assert not offenders, offenders
