from types import ModuleType

import api.social_manager.social_recon.custom_recon.platforms_probe.bluesky as bluesky
import api.social_manager.social_recon.custom_recon.platforms_probe.facebook as facebook
import api.social_manager.social_recon.custom_recon.platforms_probe.instagram as instagram
import api.social_manager.social_recon.custom_recon.platforms_probe.pinterest as pinterest
import api.social_manager.social_recon.custom_recon.platforms_probe.quora as quora
import api.social_manager.social_recon.custom_recon.platforms_probe.reddit as reddit
import api.social_manager.social_recon.custom_recon.platforms_probe.threads as threads
import api.social_manager.social_recon.custom_recon.platforms_probe.tiktok as tiktok
import api.social_manager.social_recon.custom_recon.platforms_probe.twitch as twitch
import api.social_manager.social_recon.custom_recon.platforms_probe.x as x
import api.social_manager.social_recon.custom_recon.platforms_probe.youtube as youtube
import api.social_manager.social_recon.custom_recon.platforms_probe.okru as okru
import api.social_manager.social_recon.custom_recon.platforms_probe.bilibili as bilibili
import api.social_manager.social_recon.custom_recon.platforms_probe.tieba as tieba
import api.social_manager.social_recon.custom_recon.platforms_probe.mastodon as mastodon
import api.social_manager.social_recon.custom_recon.platforms_probe.mewe as mewe
import api.social_manager.social_recon.custom_recon.platforms_probe.rumble as rumble
import api.social_manager.social_recon.custom_recon.platforms_probe.kick as kick
import api.social_manager.social_recon.custom_recon.platforms_probe.lemon8 as lemon8
import api.social_manager.social_recon.custom_recon.platforms_probe.vsco as vsco
import api.social_manager.social_recon.custom_recon.platforms_probe.flickr as flickr
import api.social_manager.social_recon.custom_recon.platforms_probe.behance as behance
import api.social_manager.social_recon.custom_recon.platforms_probe.dribbble as dribbble
import api.social_manager.social_recon.custom_recon.platforms_probe.imgur as imgur
import api.social_manager.social_recon.custom_recon.platforms_probe.artstation as artstation
import api.social_manager.social_recon.custom_recon.platforms_probe.bandcamp as bandcamp
import api.social_manager.social_recon.custom_recon.platforms_probe.lastfm as lastfm
import api.social_manager.social_recon.custom_recon.platforms_probe.goodreads as goodreads
import api.social_manager.social_recon.custom_recon.platforms_probe.letterboxd as letterboxd
import api.social_manager.social_recon.custom_recon.platforms_probe.academia as academia
import api.social_manager.social_recon.custom_recon.platforms_probe.stackoverflow as stackoverflow
import api.social_manager.social_recon.custom_recon.platforms_probe.stackexchange as stackexchange
import api.social_manager.social_recon.custom_recon.platforms_probe.github as github
import api.social_manager.social_recon.custom_recon.platforms_probe.gitlab as gitlab
import api.social_manager.social_recon.custom_recon.platforms_probe.hackernews as hackernews
import api.social_manager.social_recon.custom_recon.platforms_probe.producthunt as producthunt
import api.social_manager.social_recon.custom_recon.platforms_probe.medium as medium
import api.social_manager.social_recon.custom_recon.platforms_probe.substack as substack
import api.social_manager.social_recon.custom_recon.platforms_probe.fandom as fandom
import api.social_manager.social_recon.custom_recon.platforms_probe.steam as steam
import api.social_manager.social_recon.custom_recon.platforms_probe.roblox as roblox
import api.social_manager.social_recon.custom_recon.platforms_probe.gamejolt as gamejolt
import api.social_manager.social_recon.custom_recon.platforms_probe.myanimelist as myanimelist
import api.social_manager.social_recon.custom_recon.platforms_probe.anilist as anilist
import api.social_manager.social_recon.custom_recon.platforms_probe.interpals as interpals
import api.social_manager.social_recon.custom_recon.platforms_probe.livejournal as livejournal
import api.social_manager.social_recon.custom_recon.platforms_probe.plurk as plurk
import api.social_manager.social_recon.custom_recon.platforms_probe.misskey as misskey
import api.social_manager.social_recon.custom_recon.platforms_probe.nostr as nostr
import api.social_manager.social_recon.custom_recon.platforms_probe.microblog as microblog
import api.social_manager.social_recon.custom_recon.platforms_probe.vimeo as vimeo
import api.social_manager.social_recon.custom_recon.platforms_probe.patreon as patreon
import api.social_manager.social_recon.custom_recon.platforms_probe.linktree as linktree
import api.social_manager.social_recon.custom_recon.platforms_probe.aboutme as aboutme
import api.social_manager.social_recon.custom_recon.platforms_probe.gravatar as gravatar
import api.social_manager.social_recon.custom_recon.platforms_probe.keybase as keybase
import api.social_manager.social_recon.custom_recon.platforms_probe.dockerhub as dockerhub
import api.social_manager.social_recon.custom_recon.platforms_probe.codepen as codepen
import api.social_manager.social_recon.custom_recon.platforms_probe.chesscom as chesscom
import api.social_manager.social_recon.custom_recon.platforms_probe.lichess as lichess
import api.social_manager.social_recon.custom_recon.platforms_probe.speedrun as speedrun
import api.social_manager.social_recon.custom_recon.platforms_probe.dailymotion as dailymotion
import api.social_manager.social_recon.custom_recon.platforms_probe.giphy as giphy
import api.social_manager.social_recon.custom_recon.platforms_probe.unsplash as unsplash
import api.social_manager.social_recon.custom_recon.platforms_probe.pexels as pexels
import api.social_manager.social_recon.custom_recon.platforms_probe.wikipedia as wikipedia
import api.social_manager.social_recon.custom_recon.platforms_probe.xing as xing
import api.social_manager.social_recon.custom_recon.platforms_probe.wellfound as wellfound
import api.social_manager.social_recon.custom_recon.platforms_probe.habr as habr
import api.social_manager.social_recon.custom_recon.platforms_probe.pikabu as pikabu
import api.social_manager.social_recon.custom_recon.platforms_probe.wordpress as wordpress
import api.social_manager.social_recon.custom_recon.platforms_probe.mixcloud as mixcloud
import api.social_manager.social_recon.custom_recon.platforms_probe.itch as itch
import api.social_manager.social_recon.custom_recon.platforms_probe.minecraft as minecraft
import api.social_manager.social_recon.custom_recon.platforms_probe.osu as osu
import api.social_manager.social_recon.custom_recon.platforms_probe.codeforces as codeforces
import api.social_manager.social_recon.custom_recon.platforms_probe.leetcode as leetcode
import api.social_manager.social_recon.custom_recon.platforms_probe.hackerrank as hackerrank
import api.social_manager.social_recon.custom_recon.platforms_probe.codewars as codewars
import api.social_manager.social_recon.custom_recon.platforms_probe.kaggle as kaggle
import api.social_manager.social_recon.custom_recon.platforms_probe.crates as crates
import api.social_manager.social_recon.custom_recon.platforms_probe.devto as devto
import api.social_manager.social_recon.custom_recon.platforms_probe.hashnode as hashnode
import api.social_manager.social_recon.custom_recon.platforms_probe.gumroad as gumroad
import api.social_manager.social_recon.custom_recon.platforms_probe.redbubble as redbubble
import api.social_manager.social_recon.custom_recon.platforms_probe.kitsu as kitsu
import api.social_manager.social_recon.custom_recon.platforms_probe.rubygems as rubygems
import api.social_manager.social_recon.custom_recon.platforms_probe.scratch as scratch
import api.social_manager.social_recon.custom_recon.platforms_probe.houzz as houzz
import api.social_manager.social_recon.custom_recon.platforms_probe.smule as smule
import api.social_manager.social_recon.custom_recon.platforms_probe.notion as notion
import api.social_manager.social_recon.custom_recon.platforms_probe.tellonym as tellonym
import api.social_manager.social_recon.custom_recon.platforms_probe.bigo as bigo
import api.social_manager.social_recon.custom_recon.platforms_probe.ebay as ebay
import api.social_manager.social_recon.custom_recon.platforms_probe.slideshare as slideshare
import api.social_manager.social_recon.custom_recon.platforms_probe.audiomack as audiomack
import api.social_manager.social_recon.custom_recon.platforms_probe.beacons as beacons
import api.social_manager.social_recon.custom_recon.platforms_probe.spotify as spotify
import api.social_manager.social_recon.custom_recon.platforms_probe.trakt as trakt
import api.social_manager.social_recon.custom_recon.platforms_probe.onlyfans as onlyfans
import api.social_manager.social_recon.custom_recon.platforms_probe.figma as figma
import api.social_manager.social_recon.custom_recon.platforms_probe.bitchute as bitchute
import api.social_manager.social_recon.custom_recon.platforms_probe.amino as amino
import api.social_manager.social_recon.custom_recon.platforms_probe.badoo as badoo
import api.social_manager.social_recon.custom_recon.platforms_probe.band as band
import api.social_manager.social_recon.custom_recon.platforms_probe.bereal as bereal
import api.social_manager.social_recon.custom_recon.platforms_probe.clapper as clapper
import api.social_manager.social_recon.custom_recon.platforms_probe.couchsurfing as couchsurfing
import api.social_manager.social_recon.custom_recon.platforms_probe.dcard as dcard
import api.social_manager.social_recon.custom_recon.platforms_probe.deviantart as deviantart
import api.social_manager.social_recon.custom_recon.platforms_probe.douyin as douyin
import api.social_manager.social_recon.custom_recon.platforms_probe.fivehundredpx as fivehundredpx
import api.social_manager.social_recon.custom_recon.platforms_probe.gab as gab
import api.social_manager.social_recon.custom_recon.platforms_probe.gettr as gettr
import api.social_manager.social_recon.custom_recon.platforms_probe.kakaotalk as kakaotalk
import api.social_manager.social_recon.custom_recon.platforms_probe.kuaishou as kuaishou
import api.social_manager.social_recon.custom_recon.platforms_probe.kwai as kwai
import api.social_manager.social_recon.custom_recon.platforms_probe.likee as likee
import api.social_manager.social_recon.custom_recon.platforms_probe.meetup as meetup
import api.social_manager.social_recon.custom_recon.platforms_probe.minds as minds
import api.social_manager.social_recon.custom_recon.platforms_probe.mixi as mixi
import api.social_manager.social_recon.custom_recon.platforms_probe.mocospace as mocospace
import api.social_manager.social_recon.custom_recon.platforms_probe.nextdoor as nextdoor
import api.social_manager.social_recon.custom_recon.platforms_probe.parler as parler
import api.social_manager.social_recon.custom_recon.platforms_probe.pixiv as pixiv
import api.social_manager.social_recon.custom_recon.platforms_probe.ravelry as ravelry
import api.social_manager.social_recon.custom_recon.platforms_probe.researchgate as researchgate
import api.social_manager.social_recon.custom_recon.platforms_probe.reverbnation as reverbnation
import api.social_manager.social_recon.custom_recon.platforms_probe.soundcloud as soundcloud
import api.social_manager.social_recon.custom_recon.platforms_probe.strava as strava
import api.social_manager.social_recon.custom_recon.platforms_probe.tagged as tagged
import api.social_manager.social_recon.custom_recon.platforms_probe.telegram as telegram
import api.social_manager.social_recon.custom_recon.platforms_probe.truthsocial as truthsocial
import api.social_manager.social_recon.custom_recon.platforms_probe.tumblr as tumblr
import api.social_manager.social_recon.custom_recon.platforms_probe.vk as vk
import api.social_manager.social_recon.custom_recon.platforms_probe.wattpad as wattpad
import api.social_manager.social_recon.custom_recon.platforms_probe.weibo as weibo
import api.social_manager.social_recon.custom_recon.platforms_probe.xiaohongshu as xiaohongshu
import api.social_manager.social_recon.custom_recon.platforms_probe.zhihu as zhihu
import api.social_manager.social_recon.custom_recon.platforms_probe.linkedin as linkedin
import api.social_manager.social_recon.custom_recon.platforms_probe.snapchat as snapchat
import api.social_manager.social_recon.custom_recon.platforms_probe.imo as imo
import api.social_manager.social_recon.custom_recon.platforms_probe.line as line
import api.social_manager.social_recon.custom_recon.platforms_probe.messenger as messenger
import api.social_manager.social_recon.custom_recon.platforms_probe.navercafe as navercafe
import api.social_manager.social_recon.custom_recon.platforms_probe.qq as qq
import api.social_manager.social_recon.custom_recon.platforms_probe.viber as viber
import api.social_manager.social_recon.custom_recon.platforms_probe.wechat as wechat
import api.social_manager.social_recon.custom_recon.platforms_probe.yubo as yubo
import api.social_manager.social_recon.custom_recon.platforms_probe.discord as discord
import api.social_manager.social_recon.custom_recon.platforms_probe.whatsapp as whatsapp
import api.social_manager.social_recon.custom_recon.platforms_probe.wordpressorg as wordpressorg
import api.social_manager.social_recon.custom_recon.platforms_probe.sourceforge as sourceforge
import api.social_manager.social_recon.custom_recon.platforms_probe.blogger as blogger
import api.social_manager.social_recon.custom_recon.platforms_probe.bloggerbloggercom as bloggerbloggercom
import api.social_manager.social_recon.custom_recon.platforms_probe.tripadvisor as tripadvisor
import api.social_manager.social_recon.custom_recon.platforms_probe.myspace as myspace
import api.social_manager.social_recon.custom_recon.platforms_probe.themeforest as themeforest
import api.social_manager.social_recon.custom_recon.platforms_probe.weforum as weforum
import api.social_manager.social_recon.custom_recon.platforms_probe.freepik as freepik
import api.social_manager.social_recon.custom_recon.platforms_probe.changeorg as changeorg
import api.social_manager.social_recon.custom_recon.platforms_probe.slack as slack
import api.social_manager.social_recon.custom_recon.platforms_probe.disqus as disqus
import api.social_manager.social_recon.custom_recon.platforms_probe.npm as npm
import api.social_manager.social_recon.custom_recon.platforms_probe.digitalocean as digitalocean
import api.social_manager.social_recon.custom_recon.platforms_probe.instructables as instructables
import api.social_manager.social_recon.custom_recon.platforms_probe.ameblo as ameblo
import api.social_manager.social_recon.custom_recon.platforms_probe.huggingface as huggingface
import api.social_manager.social_recon.custom_recon.platforms_probe.laracast as laracast
import api.social_manager.social_recon.custom_recon.platforms_probe.bitbucket as bitbucket
import api.social_manager.social_recon.custom_recon.platforms_probe.upwork as upwork
import api.social_manager.social_recon.custom_recon.platforms_probe.istock as istock
import api.social_manager.social_recon.custom_recon.platforms_probe.pastebin as pastebin
import api.social_manager.social_recon.custom_recon.platforms_probe.foursquare as foursquare
import api.social_manager.social_recon.custom_recon.platforms_probe.discogs as discogs
import api.social_manager.social_recon.custom_recon.platforms_probe.kofi as kofi
import api.social_manager.social_recon.custom_recon.platforms_probe.rottentomatoes as rottentomatoes
import api.social_manager.social_recon.custom_recon.platforms_probe.smugmug as smugmug
import api.social_manager.social_recon.custom_recon.platforms_probe.duolingo as duolingo
import api.social_manager.social_recon.custom_recon.platforms_probe.ustream as ustream
import api.social_manager.social_recon.custom_recon.platforms_probe.wikidot as wikidot
import api.social_manager.social_recon.custom_recon.platforms_probe.imageshack as imageshack
import api.social_manager.social_recon.custom_recon.platforms_probe.buymeacoffee as buymeacoffee
import api.social_manager.social_recon.custom_recon.platforms_probe.gitea as gitea
import api.social_manager.social_recon.custom_recon.platforms_probe.genius as genius
import api.social_manager.social_recon.custom_recon.platforms_probe.hubpages as hubpages
import api.social_manager.social_recon.custom_recon.platforms_probe.pbase as pbase
import api.social_manager.social_recon.custom_recon.platforms_probe.geeksforgeeks as geeksforgeeks
import api.social_manager.social_recon.custom_recon.platforms_probe.codebergorg as codebergorg
import api.social_manager.social_recon.custom_recon.platforms_probe.allrecipes as allrecipes
import api.social_manager.social_recon.custom_recon.platforms_probe.codecanyon as codecanyon
import api.social_manager.social_recon.custom_recon.platforms_probe.codecademy as codecademy
import api.social_manager.social_recon.custom_recon.platforms_probe.polygon as polygon
import api.social_manager.social_recon.custom_recon.platforms_probe.pcgamer as pcgamer
import api.social_manager.social_recon.custom_recon.platforms_probe.dreamstime as dreamstime
import api.social_manager.social_recon.custom_recon.platforms_probe.speakerdeck as speakerdeck
import api.social_manager.social_recon.custom_recon.platforms_probe.nextcloudforum as nextcloudforum
import api.social_manager.social_recon.custom_recon.platforms_probe.max as max
import api.social_manager.social_recon.custom_recon.platforms_probe.tvtropes as tvtropes
import api.social_manager.social_recon.custom_recon.platforms_probe.tistory as tistory
import api.social_manager.social_recon.custom_recon.platforms_probe.jsfiddle as jsfiddle
import api.social_manager.social_recon.custom_recon.platforms_probe.gamesradar as gamesradar
import api.social_manager.social_recon.custom_recon.platforms_probe.geocaching as geocaching
import api.social_manager.social_recon.custom_recon.platforms_probe.gog as gog
import api.social_manager.social_recon.custom_recon.platforms_probe.coub as coub
import api.social_manager.social_recon.custom_recon.platforms_probe.odysee as odysee
import api.social_manager.social_recon.custom_recon.platforms_probe.replit as replit
import api.social_manager.social_recon.custom_recon.platforms_probe.hackmd as hackmd
import api.social_manager.social_recon.custom_recon.platforms_probe.inaturalist as inaturalist
import api.social_manager.social_recon.custom_recon.platforms_probe.templatemonster as templatemonster
import api.social_manager.social_recon.custom_recon.platforms_probe.teletype as teletype
import api.social_manager.social_recon.custom_recon.platforms_probe.ctan as ctan
import api.social_manager.social_recon.custom_recon.platforms_probe.opencollective as opencollective
import api.social_manager.social_recon.custom_recon.platforms_probe.giantbomb as giantbomb
import api.social_manager.social_recon.custom_recon.platforms_probe.jalbumnet as jalbumnet
import api.social_manager.social_recon.custom_recon.platforms_probe.newgrounds as newgrounds
import api.social_manager.social_recon.custom_recon.platforms_probe.slides as slides
import api.social_manager.social_recon.custom_recon.platforms_probe.ultimateguitar as ultimateguitar
import api.social_manager.social_recon.custom_recon.platforms_probe.contently as contently
import api.social_manager.social_recon.custom_recon.platforms_probe.creativemarket as creativemarket
import api.social_manager.social_recon.custom_recon.platforms_probe.opensource as opensource
import api.social_manager.social_recon.custom_recon.platforms_probe.imgflip as imgflip
import api.social_manager.social_recon.custom_recon.platforms_probe.hackaday as hackaday
import api.social_manager.social_recon.custom_recon.platforms_probe.fodors as fodors
import api.social_manager.social_recon.custom_recon.platforms_probe.designs99 as designs99
import api.social_manager.social_recon.custom_recon.platforms_probe.periscope as periscope
import api.social_manager.social_recon.custom_recon.platforms_probe.freesound as freesound
import api.social_manager.social_recon.custom_recon.platforms_probe.metalarchives as metalarchives
import api.social_manager.social_recon.custom_recon.platforms_probe.kongregate as kongregate
import api.social_manager.social_recon.custom_recon.platforms_probe.soup as soup
import api.social_manager.social_recon.custom_recon.platforms_probe.furaffinity as furaffinity
import api.social_manager.social_recon.custom_recon.platforms_probe.itemfix as itemfix
import api.social_manager.social_recon.custom_recon.platforms_probe.nintendolife as nintendolife
import api.social_manager.social_recon.custom_recon.platforms_probe.carbonmade as carbonmade
import api.social_manager.social_recon.custom_recon.platforms_probe.moddb as moddb
import api.social_manager.social_recon.custom_recon.platforms_probe.audiojungle as audiojungle
import api.social_manager.social_recon.custom_recon.platforms_probe.tinder as tinder
import api.social_manager.social_recon.custom_recon.platforms_probe.domestikaorg as domestikaorg
import api.social_manager.social_recon.custom_recon.platforms_probe.noblogs as noblogs
import api.social_manager.social_recon.custom_recon.platforms_probe.setlist as setlist
import api.social_manager.social_recon.custom_recon.platforms_probe.starcitizen as starcitizen
import api.social_manager.social_recon.custom_recon.platforms_probe.jigsawplanet as jigsawplanet
import api.social_manager.social_recon.custom_recon.platforms_probe.namuwiki as namuwiki
import api.social_manager.social_recon.custom_recon.platforms_probe.gaiaonline as gaiaonline
import api.social_manager.social_recon.custom_recon.platforms_probe.memrise as memrise
import api.social_manager.social_recon.custom_recon.platforms_probe.archiveofourown as archiveofourown
import api.social_manager.social_recon.custom_recon.platforms_probe.planetminecraft as planetminecraft
import api.social_manager.social_recon.custom_recon.platforms_probe.musescore as musescore
import api.social_manager.social_recon.custom_recon.platforms_probe.theodysseyonline as theodysseyonline
import api.social_manager.social_recon.custom_recon.platforms_probe.sportsru as sportsru
import api.social_manager.social_recon.custom_recon.platforms_probe.picsart as picsart
import api.social_manager.social_recon.custom_recon.platforms_probe.wowhead as wowhead
import api.social_manager.social_recon.custom_recon.platforms_probe.armorgames as armorgames
import api.social_manager.social_recon.custom_recon.platforms_probe.fotki as fotki
import api.social_manager.social_recon.custom_recon.platforms_probe.paltalk as paltalk
import api.social_manager.social_recon.custom_recon.platforms_probe.videohive as videohive
import api.social_manager.social_recon.custom_recon.platforms_probe.clubhouse as clubhouse
import api.social_manager.social_recon.custom_recon.platforms_probe.prozaru as prozaru
import api.social_manager.social_recon.custom_recon.platforms_probe.namepros as namepros
import api.social_manager.social_recon.custom_recon.platforms_probe.writeas as writeas
import api.social_manager.social_recon.custom_recon.platforms_probe.warriorforum as warriorforum
import api.social_manager.social_recon.custom_recon.platforms_probe.arena as arena
import api.social_manager.social_recon.custom_recon.platforms_probe.wykop as wykop
import api.social_manager.social_recon.custom_recon.platforms_probe.residentadvisor as residentadvisor
import api.social_manager.social_recon.custom_recon.platforms_probe.sporcle as sporcle
import api.social_manager.social_recon.custom_recon.platforms_probe.treehouse as treehouse
import api.social_manager.social_recon.custom_recon.platforms_probe.coroflot as coroflot
import api.social_manager.social_recon.custom_recon.platforms_probe.jeuxvideo as jeuxvideo
import api.social_manager.social_recon.custom_recon.platforms_probe.stihiru as stihiru
import api.social_manager.social_recon.custom_recon.platforms_probe.exposure as exposure
import api.social_manager.social_recon.custom_recon.platforms_probe.lyricstranslate as lyricstranslate
import api.social_manager.social_recon.custom_recon.platforms_probe.guru as guru
import api.social_manager.social_recon.custom_recon.platforms_probe.gutefrage as gutefrage
import api.social_manager.social_recon.custom_recon.platforms_probe.coderwall as coderwall
import api.social_manager.social_recon.custom_recon.platforms_probe.observable as observable
import api.social_manager.social_recon.custom_recon.platforms_probe.pushsquare as pushsquare
import api.social_manager.social_recon.custom_recon.platforms_probe.codementor as codementor
import api.social_manager.social_recon.custom_recon.platforms_probe.n4g as n4g
import api.social_manager.social_recon.custom_recon.platforms_probe.lomography as lomography
import api.social_manager.social_recon.custom_recon.platforms_probe.pixelfedsocial as pixelfedsocial
import api.social_manager.social_recon.custom_recon.platforms_probe.neoseeker as neoseeker
import api.social_manager.social_recon.custom_recon.platforms_probe.sythe as sythe
import api.social_manager.social_recon.custom_recon.platforms_probe.filmweb as filmweb
import api.social_manager.social_recon.custom_recon.platforms_probe.listal as listal
import api.social_manager.social_recon.custom_recon.platforms_probe.spatial as spatial
import api.social_manager.social_recon.custom_recon.platforms_probe.paragraph as paragraph
import api.social_manager.social_recon.custom_recon.platforms_probe.notabugorg as notabugorg
import api.social_manager.social_recon.custom_recon.platforms_probe.mydramalist as mydramalist
import api.social_manager.social_recon.custom_recon.platforms_probe.pinkbike as pinkbike
import api.social_manager.social_recon.custom_recon.platforms_probe.thechive as thechive
import api.social_manager.social_recon.custom_recon.platforms_probe.goldderby as goldderby
import api.social_manager.social_recon.custom_recon.platforms_probe.meetme as meetme
import api.social_manager.social_recon.custom_recon.platforms_probe.flyertalk as flyertalk
import api.social_manager.social_recon.custom_recon.platforms_probe.gbatempnet as gbatempnet
import api.social_manager.social_recon.custom_recon.platforms_probe.brusheezy as brusheezy
import api.social_manager.social_recon.custom_recon.platforms_probe.avforums as avforums
import api.social_manager.social_recon.custom_recon.platforms_probe.mobypicture as mobypicture
import api.social_manager.social_recon.custom_recon.platforms_probe.dlive as dlive
import api.social_manager.social_recon.custom_recon.platforms_probe.trueachievements as trueachievements
import api.social_manager.social_recon.custom_recon.platforms_probe.physicsforums as physicsforums
import api.social_manager.social_recon.custom_recon.platforms_probe.opengameart as opengameart
import api.social_manager.social_recon.custom_recon.platforms_probe.lobsters as lobsters
import api.social_manager.social_recon.custom_recon.platforms_probe.ifunny as ifunny
import api.social_manager.social_recon.custom_recon.platforms_probe.topcoder as topcoder
import api.social_manager.social_recon.custom_recon.platforms_probe.picturepushcom as picturepushcom
import api.social_manager.social_recon.custom_recon.platforms_probe.voices as voices
import api.social_manager.social_recon.custom_recon.platforms_probe.nhattaocom as nhattaocom
import api.social_manager.social_recon.custom_recon.platforms_probe.replitreplit as replitreplit
import api.social_manager.social_recon.custom_recon.platforms_probe.usernameportfolioboxnet as usernameportfolioboxnet
import api.social_manager.social_recon.custom_recon.platforms_probe.dcinside as dcinside
import api.social_manager.social_recon.custom_recon.platforms_probe.digitalpoint as digitalpoint
import api.social_manager.social_recon.custom_recon.platforms_probe.asciinema as asciinema
import api.social_manager.social_recon.custom_recon.platforms_probe.cfdonline as cfdonline
import api.social_manager.social_recon.custom_recon.platforms_probe.funnyjunk as funnyjunk
import api.social_manager.social_recon.custom_recon.platforms_probe.gloriatv as gloriatv
import api.social_manager.social_recon.custom_recon.platforms_probe.ficwad as ficwad
import api.social_manager.social_recon.custom_recon.platforms_probe.tripline as tripline
import api.social_manager.social_recon.custom_recon.platforms_probe.deepdreamgenerator as deepdreamgenerator
import api.social_manager.social_recon.custom_recon.platforms_probe.n1x as n1x
import api.social_manager.social_recon.custom_recon.platforms_probe.pokecommunity as pokecommunity
import api.social_manager.social_recon.custom_recon.platforms_probe.samlib as samlib
import api.social_manager.social_recon.custom_recon.platforms_probe.goodgameru as goodgameru
import api.social_manager.social_recon.custom_recon.platforms_probe.pling as pling
import api.social_manager.social_recon.custom_recon.platforms_probe.hardforum as hardforum
import api.social_manager.social_recon.custom_recon.platforms_probe.n23hq as n23hq
import api.social_manager.social_recon.custom_recon.platforms_probe.androidforums as androidforums
import api.social_manager.social_recon.custom_recon.platforms_probe.comedy as comedy
import api.social_manager.social_recon.custom_recon.platforms_probe.youpic as youpic
import api.social_manager.social_recon.custom_recon.platforms_probe.polarsteps as polarsteps
import api.social_manager.social_recon.custom_recon.platforms_probe.platzi as platzi
import api.social_manager.social_recon.custom_recon.platforms_probe.writingforumsorg as writingforumsorg
import api.social_manager.social_recon.custom_recon.platforms_probe.chatujmecz as chatujmecz
import api.social_manager.social_recon.custom_recon.platforms_probe.antiquers as antiquers
import api.social_manager.social_recon.custom_recon.platforms_probe.bigsoccer as bigsoccer
import api.social_manager.social_recon.custom_recon.platforms_probe.skyblock as skyblock
import api.social_manager.social_recon.custom_recon.platforms_probe.hiveblog as hiveblog
import api.social_manager.social_recon.custom_recon.platforms_probe.joyreactorcc as joyreactorcc
import api.social_manager.social_recon.custom_recon.platforms_probe.viewbug as viewbug
import api.social_manager.social_recon.custom_recon.platforms_probe.exophase as exophase
import api.social_manager.social_recon.custom_recon.platforms_probe.webdevelopercom as webdevelopercom
import api.social_manager.social_recon.custom_recon.platforms_probe.fediverseparty as fediverseparty
import api.social_manager.social_recon.custom_recon.platforms_probe.weblancer as weblancer
import api.social_manager.social_recon.custom_recon.platforms_probe.sugoidesu as sugoidesu
import api.social_manager.social_recon.custom_recon.platforms_probe.profiru as profiru
import api.social_manager.social_recon.custom_recon.platforms_probe.thoughtscom as thoughtscom
import api.social_manager.social_recon.custom_recon.platforms_probe.gapyear as gapyear
import api.social_manager.social_recon.custom_recon.platforms_probe.myinstants as myinstants
import api.social_manager.social_recon.custom_recon.platforms_probe.smokingmeatforumscom as smokingmeatforumscom
import api.social_manager.social_recon.custom_recon.platforms_probe.reibert as reibert
import api.social_manager.social_recon.custom_recon.platforms_probe.freelancehunt as freelancehunt
import api.social_manager.social_recon.custom_recon.platforms_probe.atcoder as atcoder
import api.social_manager.social_recon.custom_recon.platforms_probe.jetpunk as jetpunk
import api.social_manager.social_recon.custom_recon.platforms_probe.rappad as rappad
import api.social_manager.social_recon.custom_recon.platforms_probe.nationstatesnation as nationstatesnation
import api.social_manager.social_recon.custom_recon.platforms_probe.ethresear as ethresear
import api.social_manager.social_recon.custom_recon.platforms_probe.homebrewtalkcom as homebrewtalkcom
import api.social_manager.social_recon.custom_recon.platforms_probe.lemmyworld as lemmyworld
import api.social_manager.social_recon.custom_recon.platforms_probe.zoomirir as zoomirir
import api.social_manager.social_recon.custom_recon.platforms_probe.cent as cent
import api.social_manager.social_recon.custom_recon.platforms_probe.vjudge as vjudge
import api.social_manager.social_recon.custom_recon.platforms_probe.thesimsresource as thesimsresource
import api.social_manager.social_recon.custom_recon.platforms_probe.vgtimesgames as vgtimesgames
import api.social_manager.social_recon.custom_recon.platforms_probe.windowsforum as windowsforum
import api.social_manager.social_recon.custom_recon.platforms_probe.warpcast as warpcast
import api.social_manager.social_recon.custom_recon.platforms_probe.topmate as topmate
import api.social_manager.social_recon.custom_recon.platforms_probe.typeracer as typeracer
import api.social_manager.social_recon.custom_recon.platforms_probe.devrant as devrant
import api.social_manager.social_recon.custom_recon.platforms_probe.rmmedia as rmmedia
import api.social_manager.social_recon.custom_recon.platforms_probe.hometheaterforum as hometheaterforum
import api.social_manager.social_recon.custom_recon.platforms_probe.vlr as vlr
import api.social_manager.social_recon.custom_recon.platforms_probe.hackingwithswift as hackingwithswift
import api.social_manager.social_recon.custom_recon.platforms_probe.pokemonshowdown as pokemonshowdown
import api.social_manager.social_recon.custom_recon.platforms_probe.mynicknamecom as mynicknamecom
import api.social_manager.social_recon.custom_recon.platforms_probe.ethereummagicians as ethereummagicians
import api.social_manager.social_recon.custom_recon.platforms_probe.govloop as govloop
import api.social_manager.social_recon.custom_recon.platforms_probe.designspiration as designspiration
import api.social_manager.social_recon.custom_recon.platforms_probe.politforums as politforums
import api.social_manager.social_recon.custom_recon.platforms_probe.icheckmovies as icheckmovies
import api.social_manager.social_recon.custom_recon.platforms_probe.crevado as crevado
import api.social_manager.social_recon.custom_recon.platforms_probe.monkeytype as monkeytype
import api.social_manager.social_recon.custom_recon.platforms_probe.e621 as e621
import api.social_manager.social_recon.custom_recon.platforms_probe.gvectors as gvectors
import api.social_manager.social_recon.custom_recon.platforms_probe.rollitup as rollitup
import api.social_manager.social_recon.custom_recon.platforms_probe.riveapp as riveapp
import api.social_manager.social_recon.custom_recon.platforms_probe.mstdnio as mstdnio
import api.social_manager.social_recon.custom_recon.platforms_probe.lightstalkingcom as lightstalkingcom
import api.social_manager.social_recon.custom_recon.platforms_probe.gurushots as gurushots
import api.social_manager.social_recon.custom_recon.platforms_probe.weasyl as weasyl
import api.social_manager.social_recon.custom_recon.platforms_probe.touristlink as touristlink
import api.social_manager.social_recon.custom_recon.platforms_probe.w7forums as w7forums
import api.social_manager.social_recon.custom_recon.platforms_probe.fragment as fragment
import api.social_manager.social_recon.custom_recon.platforms_probe.allthelyrics as allthelyrics
import api.social_manager.social_recon.custom_recon.platforms_probe.nothingcommunity as nothingcommunity
import api.social_manager.social_recon.custom_recon.platforms_probe.clozemaster as clozemaster
import api.social_manager.social_recon.custom_recon.platforms_probe.n999md as n999md
import api.social_manager.social_recon.custom_recon.platforms_probe.arrse as arrse
import api.social_manager.social_recon.custom_recon.platforms_probe.n1001tracklists as n1001tracklists
import api.social_manager.social_recon.custom_recon.platforms_probe.livios as livios
import api.social_manager.social_recon.custom_recon.platforms_probe.pronounspage as pronounspage
import api.social_manager.social_recon.custom_recon.platforms_probe.au as au
import api.social_manager.social_recon.custom_recon.platforms_probe.listography as listography
import api.social_manager.social_recon.custom_recon.platforms_probe.millerovo161ru as millerovo161ru
import api.social_manager.social_recon.custom_recon.platforms_probe.rlocman as rlocman
import api.social_manager.social_recon.custom_recon.platforms_probe.aminus3 as aminus3
import api.social_manager.social_recon.custom_recon.platforms_probe.elixirforum as elixirforum
import api.social_manager.social_recon.custom_recon.platforms_probe.egpu as egpu
import api.social_manager.social_recon.custom_recon.platforms_probe.vintagemustangcom as vintagemustangcom
import api.social_manager.social_recon.custom_recon.platforms_probe.forumhr as forumhr
import api.social_manager.social_recon.custom_recon.platforms_probe.school2dobrinkaru as school2dobrinkaru
import api.social_manager.social_recon.custom_recon.platforms_probe.jigidi as jigidi
import api.social_manager.social_recon.custom_recon.platforms_probe.chemport as chemport
import api.social_manager.social_recon.custom_recon.platforms_probe.snbforums as snbforums
import api.social_manager.social_recon.custom_recon.platforms_probe.redcafe as redcafe
import api.social_manager.social_recon.custom_recon.platforms_probe.showme as showme
import api.social_manager.social_recon.custom_recon.platforms_probe.officeforums as officeforums
import api.social_manager.social_recon.custom_recon.platforms_probe.subaruoutbackorg as subaruoutbackorg
import api.social_manager.social_recon.custom_recon.platforms_probe.svtperformancecom as svtperformancecom
import api.social_manager.social_recon.custom_recon.platforms_probe.railforumscouk as railforumscouk
import api.social_manager.social_recon.custom_recon.platforms_probe.subaruforesterorg as subaruforesterorg
import api.social_manager.social_recon.custom_recon.platforms_probe.rubyforum as rubyforum
import api.social_manager.social_recon.custom_recon.platforms_probe.blipfoto as blipfoto
import api.social_manager.social_recon.custom_recon.platforms_probe.nitrotype as nitrotype
import api.social_manager.social_recon.custom_recon.platforms_probe.blast as blast
import api.social_manager.social_recon.custom_recon.platforms_probe.vishivalochkaru as vishivalochkaru
import api.social_manager.social_recon.custom_recon.platforms_probe.cslords as cslords
import api.social_manager.social_recon.custom_recon.platforms_probe.niketalk as niketalk
import api.social_manager.social_recon.custom_recon.platforms_probe.thefirearmsforum as thefirearmsforum
import api.social_manager.social_recon.custom_recon.platforms_probe.affiliatefix as affiliatefix
import api.social_manager.social_recon.custom_recon.platforms_probe.sigtalkcom as sigtalkcom
import api.social_manager.social_recon.custom_recon.platforms_probe.mirstalkeraru as mirstalkeraru
import api.social_manager.social_recon.custom_recon.platforms_probe.machelp as machelp
import api.social_manager.social_recon.custom_recon.platforms_probe.flashflashrevolution as flashflashrevolution
import api.social_manager.social_recon.custom_recon.platforms_probe.dmoj as dmoj
import api.social_manager.social_recon.custom_recon.platforms_probe.ladavestanet as ladavestanet
import api.social_manager.social_recon.custom_recon.platforms_probe.sysadmins as sysadmins
import api.social_manager.social_recon.custom_recon.platforms_probe.jeepgarageorg as jeepgarageorg
import api.social_manager.social_recon.custom_recon.platforms_probe.n4gameforum as n4gameforum
import api.social_manager.social_recon.custom_recon.platforms_probe.spells8 as spells8
import api.social_manager.social_recon.custom_recon.platforms_probe.n101010pl as n101010pl
import api.social_manager.social_recon.custom_recon.platforms_probe.cryptohack as cryptohack
import api.social_manager.social_recon.custom_recon.platforms_probe.piccsy as piccsy
import api.social_manager.social_recon.custom_recon.platforms_probe.windows10forums as windows10forums
import api.social_manager.social_recon.custom_recon.platforms_probe.ifishnet as ifishnet
import api.social_manager.social_recon.custom_recon.platforms_probe.swedroidse as swedroidse
import api.social_manager.social_recon.custom_recon.platforms_probe.cssbattle as cssbattle
import api.social_manager.social_recon.custom_recon.platforms_probe.macosx as macosx
import api.social_manager.social_recon.custom_recon.platforms_probe.religiousforums as religiousforums
import api.social_manager.social_recon.custom_recon.platforms_probe.not606com as not606com
import api.social_manager.social_recon.custom_recon.platforms_probe.gpodder as gpodder
import api.social_manager.social_recon.custom_recon.platforms_probe.md as md
import api.social_manager.social_recon.custom_recon.platforms_probe.imood as imood
import api.social_manager.social_recon.custom_recon.platforms_probe.armtorg as armtorg
import api.social_manager.social_recon.custom_recon.platforms_probe.russpussru as russpussru
import api.social_manager.social_recon.custom_recon.platforms_probe.vtwinforumcom as vtwinforumcom
import api.social_manager.social_recon.custom_recon.platforms_probe.fanficslandiacom as fanficslandiacom
import api.social_manager.social_recon.custom_recon.platforms_probe.qbn as qbn
import api.social_manager.social_recon.custom_recon.platforms_probe.lkforum as lkforum
import api.social_manager.social_recon.custom_recon.platforms_probe.clubsnapcom as clubsnapcom
import api.social_manager.social_recon.custom_recon.platforms_probe.wolpy as wolpy
import api.social_manager.social_recon.custom_recon.platforms_probe.warframemarket as warframemarket
import api.social_manager.social_recon.custom_recon.platforms_probe.cubecraftnet as cubecraftnet
import api.social_manager.social_recon.custom_recon.platforms_probe.tvgames as tvgames
import api.social_manager.social_recon.custom_recon.platforms_probe.sniperforumscom as sniperforumscom
import api.social_manager.social_recon.custom_recon.platforms_probe.izobilru as izobilru
import api.social_manager.social_recon.custom_recon.platforms_probe.goldroyal as goldroyal
import api.social_manager.social_recon.custom_recon.platforms_probe.fcrubin as fcrubin
import api.social_manager.social_recon.custom_recon.platforms_probe.oakleyforumcom as oakleyforumcom
import api.social_manager.social_recon.custom_recon.platforms_probe.hunting as hunting
import api.social_manager.social_recon.custom_recon.platforms_probe.uvelir as uvelir
import api.social_manager.social_recon.custom_recon.platforms_probe.thelion as thelion
import api.social_manager.social_recon.custom_recon.platforms_probe.xshaker as xshaker
import api.social_manager.social_recon.custom_recon.platforms_probe.nucastlecouk as nucastlecouk
import api.social_manager.social_recon.custom_recon.platforms_probe.realmeye as realmeye
import api.social_manager.social_recon.custom_recon.platforms_probe.hitmanforum as hitmanforum
import api.social_manager.social_recon.custom_recon.platforms_probe.datingru as datingru
import api.social_manager.social_recon.custom_recon.platforms_probe.volgogradforum as volgogradforum
import api.social_manager.social_recon.custom_recon.platforms_probe.tigerfancom as tigerfancom
import api.social_manager.social_recon.custom_recon.platforms_probe.impalaforumscom as impalaforumscom
import api.social_manager.social_recon.custom_recon.platforms_probe.forumjizni as forumjizni
import api.social_manager.social_recon.custom_recon.platforms_probe.xgmguru as xgmguru
import api.social_manager.social_recon.custom_recon.platforms_probe.texasguntalk as texasguntalk
import api.social_manager.social_recon.custom_recon.platforms_probe.politikforum as politikforum
import api.social_manager.social_recon.custom_recon.platforms_probe.truthbook as truthbook
import api.social_manager.social_recon.custom_recon.platforms_probe.defenceforumindia as defenceforumindia
import api.social_manager.social_recon.custom_recon.platforms_probe.forumsdromru as forumsdromru
import api.social_manager.social_recon.custom_recon.platforms_probe.antiquebottles as antiquebottles
import api.social_manager.social_recon.custom_recon.platforms_probe.ridemonkeycom as ridemonkeycom
import api.social_manager.social_recon.custom_recon.platforms_probe.discussfastpitch as discussfastpitch
import api.social_manager.social_recon.custom_recon.platforms_probe.avtoforumname as avtoforumname
import api.social_manager.social_recon.custom_recon.platforms_probe.spaces as spaces
import api.social_manager.social_recon.custom_recon.platforms_probe.russianfi as russianfi
import api.social_manager.social_recon.custom_recon.platforms_probe.xtratimeorg as xtratimeorg
import api.social_manager.social_recon.custom_recon.platforms_probe.nikoncafecom as nikoncafecom
import api.social_manager.social_recon.custom_recon.platforms_probe.cowboyszonecom as cowboyszonecom
import api.social_manager.social_recon.custom_recon.platforms_probe.thebuddyforum as thebuddyforum
import api.social_manager.social_recon.custom_recon.platforms_probe.vauxhallownersnetworkcouk as vauxhallownersnetworkcouk
import api.social_manager.social_recon.custom_recon.platforms_probe.erogenclub as erogenclub
import api.social_manager.social_recon.custom_recon.platforms_probe.mineplexcom as mineplexcom
import api.social_manager.social_recon.custom_recon.platforms_probe.codersrank as codersrank
import api.social_manager.social_recon.custom_recon.platforms_probe.worldofplayers as worldofplayers
from api.social_manager.social_recon.constants.custom_recon_constants import RegistryConstants

platforms: dict[str, ModuleType] = {
    "facebook": facebook,
    "instagram": instagram,
    "youtube": youtube,
    "tiktok": tiktok,
    "x": x,
    "reddit": reddit,
    "pinterest": pinterest,
    "threads": threads,
    "bluesky": bluesky,
    "quora": quora,
    "twitch": twitch,
    "okru": okru,
    "bilibili": bilibili,
    "tieba": tieba,
    "mastodon": mastodon,
    "mewe": mewe,
    "rumble": rumble,
    "kick": kick,
    "lemon8": lemon8,
    "vsco": vsco,
    "flickr": flickr,
    "behance": behance,
    "dribbble": dribbble,
    "imgur": imgur,
    "artstation": artstation,
    "bandcamp": bandcamp,
    "lastfm": lastfm,
    "goodreads": goodreads,
    "letterboxd": letterboxd,
    "academia": academia,
    "stackoverflow": stackoverflow,
    "stackexchange": stackexchange,
    "github": github,
    "gitlab": gitlab,
    "hackernews": hackernews,
    "producthunt": producthunt,
    "medium": medium,
    "substack": substack,
    "fandom": fandom,
    "steam": steam,
    "roblox": roblox,
    "gamejolt": gamejolt,
    "myanimelist": myanimelist,
    "anilist": anilist,
    "interpals": interpals,
    "livejournal": livejournal,
    "plurk": plurk,
    "misskey": misskey,
    "nostr": nostr,
    "microblog": microblog,
    "vimeo": vimeo,
    "patreon": patreon,
    "linktree": linktree,
    "aboutme": aboutme,
    "gravatar": gravatar,
    "keybase": keybase,
    "dockerhub": dockerhub,
    "codepen": codepen,
    "chesscom": chesscom,
    "lichess": lichess,
    "speedrun": speedrun,
    "dailymotion": dailymotion,
    "giphy": giphy,
    "unsplash": unsplash,
    "pexels": pexels,
    "wikipedia": wikipedia,
    "xing": xing,
    "wellfound": wellfound,
    "habr": habr,
    "pikabu": pikabu,
    "wordpress": wordpress,
    "mixcloud": mixcloud,
    "itch": itch,
    "minecraft": minecraft,
    "osu": osu,
    "codeforces": codeforces,
    "leetcode": leetcode,
    "hackerrank": hackerrank,
    "codewars": codewars,
    "kaggle": kaggle,
    "crates": crates,
    "devto": devto,
    "hashnode": hashnode,
    "gumroad": gumroad,
    "redbubble": redbubble,
    "kitsu": kitsu,
    "rubygems": rubygems,
    "scratch": scratch,
    "houzz": houzz,
    "smule": smule,
    "notion": notion,
    "tellonym": tellonym,
    "bigo": bigo,
    "ebay": ebay,
    "slideshare": slideshare,
    "audiomack": audiomack,
    "beacons": beacons,
    "spotify": spotify,
    "trakt": trakt,
    "onlyfans": onlyfans,
    "figma": figma,
    "bitchute": bitchute,
    "amino": amino,
    "badoo": badoo,
    "band": band,
    "bereal": bereal,
    "clapper": clapper,
    "couchsurfing": couchsurfing,
    "dcard": dcard,
    "deviantart": deviantart,
    "douyin": douyin,
    "fivehundredpx": fivehundredpx,
    "gab": gab,
    "gettr": gettr,
    "kakaotalk": kakaotalk,
    "kuaishou": kuaishou,
    "kwai": kwai,
    "likee": likee,
    "meetup": meetup,
    "minds": minds,
    "mixi": mixi,
    "mocospace": mocospace,
    "nextdoor": nextdoor,
    "parler": parler,
    "pixiv": pixiv,
    "ravelry": ravelry,
    "researchgate": researchgate,
    "reverbnation": reverbnation,
    "soundcloud": soundcloud,
    "strava": strava,
    "tagged": tagged,
    "telegram": telegram,
    "truthsocial": truthsocial,
    "tumblr": tumblr,
    "vk": vk,
    "wattpad": wattpad,
    "weibo": weibo,
    "xiaohongshu": xiaohongshu,
    "zhihu": zhihu,
    "linkedin": linkedin,
    "snapchat": snapchat,
    "imo": imo,
    "line": line,
    "messenger": messenger,
    "navercafe": navercafe,
    "qq": qq,
    "viber": viber,
    "wechat": wechat,
    "yubo": yubo,
    "discord": discord,
    "whatsapp": whatsapp,
    "wordpressorg": wordpressorg,
    "sourceforge": sourceforge,
    "blogger": blogger,
    "bloggerbloggercom": bloggerbloggercom,
    "tripadvisor": tripadvisor,
    "myspace": myspace,
    "themeforest": themeforest,
    "weforum": weforum,
    "freepik": freepik,
    "changeorg": changeorg,
    "slack": slack,
    "disqus": disqus,
    "npm": npm,
    "digitalocean": digitalocean,
    "instructables": instructables,
    "ameblo": ameblo,
    "huggingface": huggingface,
    "laracast": laracast,
    "bitbucket": bitbucket,
    "upwork": upwork,
    "istock": istock,
    "pastebin": pastebin,
    "foursquare": foursquare,
    "discogs": discogs,
    "kofi": kofi,
    "rottentomatoes": rottentomatoes,
    "smugmug": smugmug,
    "duolingo": duolingo,
    "ustream": ustream,
    "wikidot": wikidot,
    "imageshack": imageshack,
    "buymeacoffee": buymeacoffee,
    "gitea": gitea,
    "genius": genius,
    "hubpages": hubpages,
    "pbase": pbase,
    "geeksforgeeks": geeksforgeeks,
    "codebergorg": codebergorg,
    "allrecipes": allrecipes,
    "codecanyon": codecanyon,
    "codecademy": codecademy,
    "polygon": polygon,
    "pcgamer": pcgamer,
    "dreamstime": dreamstime,
    "speakerdeck": speakerdeck,
    "nextcloudforum": nextcloudforum,
    "max": max,
    "tvtropes": tvtropes,
    "tistory": tistory,
    "jsfiddle": jsfiddle,
    "gamesradar": gamesradar,
    "geocaching": geocaching,
    "gog": gog,
    "coub": coub,
    "odysee": odysee,
    "replit": replit,
    "hackmd": hackmd,
    "inaturalist": inaturalist,
    "templatemonster": templatemonster,
    "teletype": teletype,
    "ctan": ctan,
    "opencollective": opencollective,
    "giantbomb": giantbomb,
    "jalbumnet": jalbumnet,
    "newgrounds": newgrounds,
    "slides": slides,
    "ultimateguitar": ultimateguitar,
    "contently": contently,
    "creativemarket": creativemarket,
    "opensource": opensource,
    "imgflip": imgflip,
    "hackaday": hackaday,
    "fodors": fodors,
    "designs99": designs99,
    "periscope": periscope,
    "freesound": freesound,
    "metalarchives": metalarchives,
    "kongregate": kongregate,
    "soup": soup,
    "furaffinity": furaffinity,
    "itemfix": itemfix,
    "nintendolife": nintendolife,
    "carbonmade": carbonmade,
    "moddb": moddb,
    "audiojungle": audiojungle,
    "tinder": tinder,
    "domestikaorg": domestikaorg,
    "noblogs": noblogs,
    "setlist": setlist,
    "starcitizen": starcitizen,
    "jigsawplanet": jigsawplanet,
    "namuwiki": namuwiki,
    "gaiaonline": gaiaonline,
    "memrise": memrise,
    "archiveofourown": archiveofourown,
    "planetminecraft": planetminecraft,
    "musescore": musescore,
    "theodysseyonline": theodysseyonline,
    "sportsru": sportsru,
    "picsart": picsart,
    "wowhead": wowhead,
    "armorgames": armorgames,
    "fotki": fotki,
    "paltalk": paltalk,
    "videohive": videohive,
    "clubhouse": clubhouse,
    "prozaru": prozaru,
    "namepros": namepros,
    "writeas": writeas,
    "warriorforum": warriorforum,
    "arena": arena,
    "wykop": wykop,
    "residentadvisor": residentadvisor,
    "sporcle": sporcle,
    "treehouse": treehouse,
    "coroflot": coroflot,
    "jeuxvideo": jeuxvideo,
    "stihiru": stihiru,
    "exposure": exposure,
    "lyricstranslate": lyricstranslate,
    "guru": guru,
    "gutefrage": gutefrage,
    "coderwall": coderwall,
    "observable": observable,
    "pushsquare": pushsquare,
    "codementor": codementor,
    "n4g": n4g,
    "lomography": lomography,
    "pixelfedsocial": pixelfedsocial,
    "neoseeker": neoseeker,
    "sythe": sythe,
    "filmweb": filmweb,
    "listal": listal,
    "spatial": spatial,
    "paragraph": paragraph,
    "notabugorg": notabugorg,
    "mydramalist": mydramalist,
    "pinkbike": pinkbike,
    "thechive": thechive,
    "goldderby": goldderby,
    "meetme": meetme,
    "flyertalk": flyertalk,
    "gbatempnet": gbatempnet,
    "brusheezy": brusheezy,
    "avforums": avforums,
    "mobypicture": mobypicture,
    "dlive": dlive,
    "trueachievements": trueachievements,
    "physicsforums": physicsforums,
    "opengameart": opengameart,
    "lobsters": lobsters,
    "ifunny": ifunny,
    "topcoder": topcoder,
    "picturepushcom": picturepushcom,
    "voices": voices,
    "nhattaocom": nhattaocom,
    "replitreplit": replitreplit,
    "usernameportfolioboxnet": usernameportfolioboxnet,
    "dcinside": dcinside,
    "digitalpoint": digitalpoint,
    "asciinema": asciinema,
    "cfdonline": cfdonline,
    "funnyjunk": funnyjunk,
    "gloriatv": gloriatv,
    "ficwad": ficwad,
    "tripline": tripline,
    "deepdreamgenerator": deepdreamgenerator,
    "n1x": n1x,
    "pokecommunity": pokecommunity,
    "samlib": samlib,
    "goodgameru": goodgameru,
    "pling": pling,
    "hardforum": hardforum,
    "n23hq": n23hq,
    "androidforums": androidforums,
    "comedy": comedy,
    "youpic": youpic,
    "polarsteps": polarsteps,
    "platzi": platzi,
    "writingforumsorg": writingforumsorg,
    "chatujmecz": chatujmecz,
    "antiquers": antiquers,
    "bigsoccer": bigsoccer,
    "skyblock": skyblock,
    "hiveblog": hiveblog,
    "joyreactorcc": joyreactorcc,
    "viewbug": viewbug,
    "exophase": exophase,
    "webdevelopercom": webdevelopercom,
    "fediverseparty": fediverseparty,
    "weblancer": weblancer,
    "sugoidesu": sugoidesu,
    "profiru": profiru,
    "thoughtscom": thoughtscom,
    "gapyear": gapyear,
    "myinstants": myinstants,
    "smokingmeatforumscom": smokingmeatforumscom,
    "reibert": reibert,
    "freelancehunt": freelancehunt,
    "atcoder": atcoder,
    "jetpunk": jetpunk,
    "rappad": rappad,
    "nationstatesnation": nationstatesnation,
    "ethresear": ethresear,
    "homebrewtalkcom": homebrewtalkcom,
    "lemmyworld": lemmyworld,
    "zoomirir": zoomirir,
    "cent": cent,
    "vjudge": vjudge,
    "thesimsresource": thesimsresource,
    "vgtimesgames": vgtimesgames,
    "windowsforum": windowsforum,
    "warpcast": warpcast,
    "topmate": topmate,
    "typeracer": typeracer,
    "devrant": devrant,
    "rmmedia": rmmedia,
    "hometheaterforum": hometheaterforum,
    "vlr": vlr,
    "hackingwithswift": hackingwithswift,
    "pokemonshowdown": pokemonshowdown,
    "mynicknamecom": mynicknamecom,
    "ethereummagicians": ethereummagicians,
    "govloop": govloop,
    "designspiration": designspiration,
    "politforums": politforums,
    "icheckmovies": icheckmovies,
    "crevado": crevado,
    "monkeytype": monkeytype,
    "e621": e621,
    "gvectors": gvectors,
    "rollitup": rollitup,
    "riveapp": riveapp,
    "mstdnio": mstdnio,
    "lightstalkingcom": lightstalkingcom,
    "gurushots": gurushots,
    "weasyl": weasyl,
    "touristlink": touristlink,
    "w7forums": w7forums,
    "fragment": fragment,
    "allthelyrics": allthelyrics,
    "nothingcommunity": nothingcommunity,
    "clozemaster": clozemaster,
    "n999md": n999md,
    "arrse": arrse,
    "n1001tracklists": n1001tracklists,
    "livios": livios,
    "pronounspage": pronounspage,
    "au": au,
    "listography": listography,
    "millerovo161ru": millerovo161ru,
    "rlocman": rlocman,
    "aminus3": aminus3,
    "elixirforum": elixirforum,
    "egpu": egpu,
    "vintagemustangcom": vintagemustangcom,
    "forumhr": forumhr,
    "school2dobrinkaru": school2dobrinkaru,
    "jigidi": jigidi,
    "chemport": chemport,
    "snbforums": snbforums,
    "redcafe": redcafe,
    "showme": showme,
    "officeforums": officeforums,
    "subaruoutbackorg": subaruoutbackorg,
    "svtperformancecom": svtperformancecom,
    "railforumscouk": railforumscouk,
    "subaruforesterorg": subaruforesterorg,
    "rubyforum": rubyforum,
    "blipfoto": blipfoto,
    "nitrotype": nitrotype,
    "blast": blast,
    "vishivalochkaru": vishivalochkaru,
    "cslords": cslords,
    "niketalk": niketalk,
    "thefirearmsforum": thefirearmsforum,
    "affiliatefix": affiliatefix,
    "sigtalkcom": sigtalkcom,
    "mirstalkeraru": mirstalkeraru,
    "machelp": machelp,
    "flashflashrevolution": flashflashrevolution,
    "dmoj": dmoj,
    "ladavestanet": ladavestanet,
    "sysadmins": sysadmins,
    "jeepgarageorg": jeepgarageorg,
    "n4gameforum": n4gameforum,
    "spells8": spells8,
    "n101010pl": n101010pl,
    "cryptohack": cryptohack,
    "piccsy": piccsy,
    "windows10forums": windows10forums,
    "ifishnet": ifishnet,
    "swedroidse": swedroidse,
    "cssbattle": cssbattle,
    "macosx": macosx,
    "religiousforums": religiousforums,
    "not606com": not606com,
    "gpodder": gpodder,
    "md": md,
    "imood": imood,
    "armtorg": armtorg,
    "russpussru": russpussru,
    "vtwinforumcom": vtwinforumcom,
    "fanficslandiacom": fanficslandiacom,
    "qbn": qbn,
    "lkforum": lkforum,
    "clubsnapcom": clubsnapcom,
    "wolpy": wolpy,
    "warframemarket": warframemarket,
    "cubecraftnet": cubecraftnet,
    "tvgames": tvgames,
    "sniperforumscom": sniperforumscom,
    "izobilru": izobilru,
    "goldroyal": goldroyal,
    "fcrubin": fcrubin,
    "oakleyforumcom": oakleyforumcom,
    "hunting": hunting,
    "uvelir": uvelir,
    "thelion": thelion,
    "xshaker": xshaker,
    "nucastlecouk": nucastlecouk,
    "realmeye": realmeye,
    "hitmanforum": hitmanforum,
    "datingru": datingru,
    "volgogradforum": volgogradforum,
    "tigerfancom": tigerfancom,
    "impalaforumscom": impalaforumscom,
    "forumjizni": forumjizni,
    "xgmguru": xgmguru,
    "texasguntalk": texasguntalk,
    "politikforum": politikforum,
    "truthbook": truthbook,
    "defenceforumindia": defenceforumindia,
    "forumsdromru": forumsdromru,
    "antiquebottles": antiquebottles,
    "ridemonkeycom": ridemonkeycom,
    "discussfastpitch": discussfastpitch,
    "avtoforumname": avtoforumname,
    "spaces": spaces,
    "russianfi": russianfi,
    "xtratimeorg": xtratimeorg,
    "nikoncafecom": nikoncafecom,
    "cowboyszonecom": cowboyszonecom,
    "thebuddyforum": thebuddyforum,
    "vauxhallownersnetworkcouk": vauxhallownersnetworkcouk,
    "erogenclub": erogenclub,
    "mineplexcom": mineplexcom,
    "codersrank": codersrank,
    "worldofplayers": worldofplayers,
}


def resolve(name: str) -> ModuleType | None:
    key = (name or "").strip().lower()
    return platforms.get(RegistryConstants.ALIASES.get(key, key))


def supported(module: ModuleType) -> bool:
    return getattr(module.constants, "SUPPORTED", True)


def names() -> tuple[str, ...]:
    return tuple(platforms)
